package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"errors"
	"fmt"
	"time"

	pgx "github.com/jackc/pgx/v5"
	"github.com/yourorg/ztna/controller/graph"
	"github.com/yourorg/ztna/controller/internal/invitation"
	"github.com/yourorg/ztna/controller/internal/tenant"
)

// CreateInvitation is the resolver for the createInvitation field.
// Admin-only — role check enforced here (GraphQL has no per-field middleware).
func (r *mutationResolver) CreateInvitation(ctx context.Context, email string) (*graph.Invitation, error) {
	tc, ok := tenant.Get(ctx)
	if !ok {
		return nil, fmt.Errorf("unauthenticated")
	}
	if tc.Role != "admin" {
		return nil, fmt.Errorf("forbidden: only admins can create invitations")
	}

	inv, err := r.InvitationStore.CreateInvitation(ctx, email, tc.TenantID, tc.UserID)
	if err != nil {
		return nil, fmt.Errorf("create invitation: %w", err)
	}

	var workspaceName string
	r.Pool.QueryRow(ctx, `SELECT name FROM workspaces WHERE id = $1`, tc.TenantID).Scan(&workspaceName) //nolint:errcheck
	if workspaceName == "" {
		workspaceName = "your workspace"
	}
	go r.InvitationEmailer.SendInvitation(inv, workspaceName) //nolint:errcheck

	return invitationToGQL(inv), nil
}

// RevokeDevice is the resolver for the revokeDevice field.
func (r *mutationResolver) RevokeDevice(ctx context.Context, deviceID string) (bool, error) {
	tc, ok := tenant.Get(ctx)
	if !ok {
		return false, fmt.Errorf("unauthenticated")
	}
	if tc.Role != "admin" {
		return false, fmt.Errorf("forbidden: only admins can revoke devices")
	}

	var discardedID string
	err := r.Pool.QueryRow(ctx,
		`UPDATE client_devices
		    SET revoked_at = NOW()
		  WHERE id = $1
		    AND workspace_id = $2
		    AND revoked_at IS NULL
		 RETURNING id`,
		deviceID, tc.TenantID,
	).Scan(&discardedID)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return false, fmt.Errorf("revoke device: device not found or already revoked")
		}
		return false, fmt.Errorf("revoke device: %w", err)
	}

	return true, nil
}

// MyDevices is the resolver for the myDevices field.
func (r *queryResolver) MyDevices(ctx context.Context) ([]*graph.ClientDevice, error) {
	tc, ok := tenant.Get(ctx)
	if !ok {
		return nil, fmt.Errorf("unauthenticated")
	}

	rows, err := r.Pool.Query(ctx,
		`SELECT id, user_id, name, os, spiffe_id, cert_not_after, last_seen_at, created_at, revoked_at
		   FROM client_devices
		  WHERE user_id = $1
		    AND workspace_id = $2
		  ORDER BY created_at DESC`,
		tc.UserID, tc.TenantID,
	)
	if err != nil {
		return nil, fmt.Errorf("query client devices: %w", err)
	}
	defer rows.Close()

	var devices []*graph.ClientDevice
	for rows.Next() {
		d, err := scanClientDevice(rows)
		if err != nil {
			return nil, fmt.Errorf("scan client device: %w", err)
		}
		devices = append(devices, d)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("iterate client devices: %w", err)
	}

	return devices, nil
}

// ClientDevices is the resolver for the clientDevices field.
func (r *queryResolver) ClientDevices(ctx context.Context) ([]*graph.ClientDevice, error) {
	tc, ok := tenant.Get(ctx)
	if !ok {
		return nil, fmt.Errorf("unauthenticated")
	}
	if tc.Role != "admin" {
		return nil, fmt.Errorf("forbidden: only admins can list all devices")
	}

	rows, err := r.Pool.Query(ctx,
		`SELECT id, user_id, name, os, spiffe_id, cert_not_after, last_seen_at, created_at, revoked_at
		   FROM client_devices
		  WHERE workspace_id = $1
		  ORDER BY created_at DESC`,
		tc.TenantID,
	)
	if err != nil {
		return nil, fmt.Errorf("query client devices: %w", err)
	}
	defer rows.Close()

	var devices []*graph.ClientDevice
	for rows.Next() {
		d, err := scanClientDevice(rows)
		if err != nil {
			return nil, fmt.Errorf("scan client device: %w", err)
		}
		devices = append(devices, d)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("iterate client devices: %w", err)
	}

	return devices, nil
}

// Invitation is the resolver for the invitation field.
// Public — returns nil for unknown/expired/non-pending tokens without leaking details.
func (r *queryResolver) Invitation(ctx context.Context, token string) (*graph.Invitation, error) {
	inv, err := r.InvitationStore.GetByToken(ctx, token)
	if errors.Is(err, invitation.ErrNotFound) {
		return nil, nil //nolint:nilnil
	}
	if err != nil {
		return nil, fmt.Errorf("lookup invitation: %w", err)
	}

	if inv.Status != "pending" || time.Now().After(inv.ExpiresAt) {
		return nil, nil //nolint:nilnil
	}

	return invitationToGQL(inv), nil
}
