package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"fmt"

	"github.com/yourorg/ztna/controller/graph"
)

// CreateInvitation is the resolver for the createInvitation field.
func (r *mutationResolver) CreateInvitation(ctx context.Context, email string) (*graph.Invitation, error) {
	panic(fmt.Errorf("not implemented: CreateInvitation - createInvitation"))
}

// MyDevices is the resolver for the myDevices field.
func (r *queryResolver) MyDevices(ctx context.Context) ([]*graph.ClientDevice, error) {
	panic(fmt.Errorf("not implemented: MyDevices - myDevices"))
}

// Invitation is the resolver for the invitation field.
func (r *queryResolver) Invitation(ctx context.Context, token string) (*graph.Invitation, error) {
	panic(fmt.Errorf("not implemented: Invitation - invitation"))
}
