package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"errors"
	"fmt"
	"log"
	"strings"

	pgx "github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/yourorg/ztna/controller/graph"
	"github.com/yourorg/ztna/controller/internal/apperr"
	"github.com/yourorg/ztna/controller/internal/tenant"
)

// CreateRemoteNetwork is the resolver for the createRemoteNetwork field.
func (r *mutationResolver) CreateRemoteNetwork(ctx context.Context, name string, location graph.NetworkLocation) (*graph.RemoteNetwork, error) {
	tc := tenant.MustGet(ctx)

	rn, err := scanRemoteNetwork(r.TenantDB.QueryRow(ctx,
		`INSERT INTO remote_networks (tenant_id, name, location)
		 VALUES ($1, $2, $3)
		 RETURNING id, name, location, status, created_at`,
		tc.TenantID, name, strings.ToLower(string(location)),
	))
	if err != nil {
		return nil, fmt.Errorf("create remote network: %w", err)
	}

	return rn, nil
}

// DeleteRemoteNetwork is the resolver for the deleteRemoteNetwork field.
func (r *mutationResolver) DeleteRemoteNetwork(ctx context.Context, id string) (bool, error) {
	tc := tenant.MustGet(ctx)

	var discardedID string
	err := r.TenantDB.QueryRow(ctx,
		`UPDATE remote_networks
		    SET status = 'deleted', updated_at = NOW()
		  WHERE id = $1
		    AND tenant_id = $2
		    AND status = 'active'
		    AND NOT EXISTS (
		        SELECT 1 FROM connectors
		         WHERE remote_network_id = $1
		           AND tenant_id = $2
		           AND status NOT IN ('pending', 'revoked')
		    )
		 RETURNING id`,
		id, tc.TenantID,
	).Scan(&discardedID)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return false, fmt.Errorf("delete remote network: network not found, already deleted, or has active connectors")
		}
		return false, fmt.Errorf("delete remote network: %w", err)
	}

	return true, nil
}

// GenerateConnectorToken is the resolver for the generateConnectorToken field.
func (r *mutationResolver) GenerateConnectorToken(ctx context.Context, remoteNetworkID string, connectorName string) (*graph.ConnectorToken, error) {
	tc := tenant.MustGet(ctx)

	name, vErr := validateAgentName("connector", connectorName)
	if vErr != nil {
		return nil, vErr
	}

	var rnStatus string
	err := r.TenantDB.QueryRow(ctx,
		`SELECT status FROM remote_networks WHERE id = $1 AND tenant_id = $2`,
		remoteNetworkID, tc.TenantID,
	).Scan(&rnStatus)
	if err != nil {
		return nil, apperr.UserErrorf("remote network not found")
	}
	if rnStatus != "active" {
		return nil, apperr.UserErrorf("remote network is %q, expected active", rnStatus)
	}

	var connectorID string
	err = r.TenantDB.QueryRow(ctx,
		`INSERT INTO connectors (tenant_id, remote_network_id, name)
		 VALUES ($1, $2, $3)
		 RETURNING id`,
		tc.TenantID, remoteNetworkID, name,
	).Scan(&connectorID)
	if err != nil {
		var pgErr *pgconn.PgError
		if errors.As(err, &pgErr) && pgErr.Code == "23505" { // unique_violation
			return nil, apperr.UserErrorf("a connector named %q already exists", name)
		}
		return nil, fmt.Errorf("generate connector token: insert connector: %w", err)
	}

	// Token minting is lazy: the create path only reserves the pending row.
	// The enrollment token (JWT + Redis jti + install command) is issued on
	// demand by the REST endpoint POST /api/connectors/{id}/token when the
	// detail page loads. See ADR-008. This keeps the credential off the
	// GraphQL/Apollo-cache surface and avoids minting a token that's discarded.
	return &graph.ConnectorToken{ConnectorID: connectorID}, nil
}

// ReenrollConnector is the resolver for the reenrollConnector field.
func (r *mutationResolver) ReenrollConnector(ctx context.Context, id string) (bool, error) {
	tc := tenant.MustGet(ctx)

	// ADR-024: certificate expiry is a HARD trust boundary. Renewal always
	// requires a currently-valid certificate, and an expired one must re-enrol.
	// Nothing here relaxes that — `Enroll` still accepts only a pending connector
	// and RegenerateTokenHandler still issues a token only for a pending one.
	// What was missing was a supported way to REACH pending without destroying the
	// connector's identity: the only route was revoke + create-new, which mints a
	// new connector id and so orphans every shield bound to the old one (the exact
	// cascade ADR-024 records as instance 1). Keeping the id is the whole point.
	//
	// The status gate is load-bearing, not defensive:
	//   - 'revoked'      → refused. Revocation is absolute; this must never
	//                      become a way to un-revoke.
	//   - 'active'       → refused. A pending connector is excluded from ACL
	//                      snapshots (policy/store.go: `c.status = 'active'`), so
	//                      flipping a WORKING connector would take its resources
	//                      offline. That is an outage disguised as a repair.
	//   - 'disconnected' → allowed. This is the expired-cert case: the connector
	//                      cannot heartbeat, so the disconnect watcher has already
	//                      marked it, and it is already out of the ACL snapshots.
	//   - 'pending'      → allowed, so the action is idempotent and a second click
	//                      just yields a fresh token.
	//
	// Cleared columns are exactly the credential-bearing ones that Enroll rewrites
	// (enrollment.go: status, cert_serial, cert_not_after, enrollment_token_jti).
	// trust_domain, hostname and version are left alone — Enroll overwrites them —
	// and remote_network_id and the id itself are never touched.
	var newStatus string
	err := r.TenantDB.QueryRow(ctx,
		`UPDATE connectors
		    SET status               = 'pending',
		        cert_serial          = NULL,
		        cert_not_after       = NULL,
		        enrollment_token_jti = NULL,
		        updated_at           = NOW()
		  WHERE id = $1
		    AND tenant_id = $2
		    AND status IN ('disconnected', 'pending')
		 RETURNING status`,
		id, tc.TenantID,
	).Scan(&newStatus)
	if errors.Is(err, pgx.ErrNoRows) {
		// Distinguish the three no-op cases, because "nothing happened" is the
		// least useful thing to tell an operator mid-recovery.
		var current string
		if qErr := r.TenantDB.QueryRow(ctx,
			`SELECT status FROM connectors WHERE id = $1 AND tenant_id = $2`,
			id, tc.TenantID,
		).Scan(&current); qErr != nil {
			return false, apperr.UserErrorf("connector not found")
		}
		switch current {
		case "revoked":
			return false, apperr.UserErrorf("connector is revoked; revocation cannot be undone — create a new connector instead")
		case "active":
			return false, apperr.UserErrorf("connector is active; re-enrolling it would remove it from ACL snapshots and take its resources offline. Revoke it first if you intend to replace it")
		default:
			return false, apperr.UserErrorf("connector status is %q, expected disconnected or pending", current)
		}
	}
	if err != nil {
		return false, fmt.Errorf("reenroll connector: %w", err)
	}

	// The connector's shields and their resources are deliberately NOT touched:
	// keeping the connector id is what preserves them, and that is the difference
	// between this and revoke + create-new.
	return true, nil
}

// RevokeConnector is the resolver for the revokeConnector field.
func (r *mutationResolver) RevokeConnector(ctx context.Context, id string) (bool, error) {
	tc := tenant.MustGet(ctx)

	var discardedID string
	err := r.TenantDB.QueryRow(ctx,
		`UPDATE connectors
		    SET status            = 'revoked',
		        revoked_at        = NOW(),
		        revocation_reason = 'revoked via admin API',
		        updated_at        = NOW()
		  WHERE id = $1
		    AND tenant_id = $2
		    AND status IN ('active', 'disconnected')
		    AND revoked_at IS NULL
		 RETURNING id`,
		id, tc.TenantID,
	).Scan(&discardedID)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return false, fmt.Errorf("revoke connector: connector not found or not in revocable status")
		}
		return false, fmt.Errorf("revoke connector: %w", err)
	}

	// Drop the revoked connector from BOTH planes immediately: the ACL
	// (availability) and the transport (connectivity) snapshots. Without this,
	// the connector lingers in the cached snapshots until they happen to be
	// invalidated. The guarded heartbeat UPDATE (control_stream) prevents the
	// connector from resurrecting itself and closes its live stream on the next
	// heartbeat.
	if r.PolicyNotifier != nil {
		if err := r.PolicyNotifier.NotifyPolicyChange(ctx, tc.TenantID); err != nil {
			return false, fmt.Errorf("revoke connector: notify policy change: %w", err)
		}
	}
	if r.TransportNotifier != nil {
		if err := r.TransportNotifier.NotifyTopologyChange(ctx, tc.TenantID, []string{id}); err != nil {
			return false, fmt.Errorf("revoke connector: notify topology change: %w", err)
		}
	}

	return true, nil
}

// DeleteConnector is the resolver for the deleteConnector field.
func (r *mutationResolver) DeleteConnector(ctx context.Context, id string) (bool, error) {
	tc := tenant.MustGet(ctx)

	tx, err := r.TenantDB.BeginTx(ctx)
	if err != nil {
		return false, fmt.Errorf("delete connector: begin: %w", err)
	}
	defer func() { _ = tx.Rollback(ctx) }()

	// Demote BEFORE the delete: `shields.connector_id` cascades, and
	// `resources.shield_id` is ON DELETE SET NULL, which nulls the FK but leaves
	// `status` at 'protected' — a resource claiming shield delivery with no shield.
	// See demoteOrphanedResources.
	demoted, err := demoteResourcesForConnectorShields(ctx, tx, tc.TenantID, id)
	if err != nil {
		return false, fmt.Errorf("delete connector: demote shield-bound resources: %w", err)
	}

	var discardedID string
	err = tx.QueryRow(ctx,
		`DELETE FROM connectors
		  WHERE id = $1
		    AND tenant_id = $2
		    AND status IN ('pending', 'revoked')
		 RETURNING id`,
		id, tc.TenantID,
	).Scan(&discardedID)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return false, fmt.Errorf("delete connector: connector not found or must be revoked before deletion")
		}
		return false, fmt.Errorf("delete connector: %w", err)
	}

	if err := tx.Commit(ctx); err != nil {
		return false, fmt.Errorf("delete connector: commit: %w", err)
	}
	if demoted > 0 {
		log.Printf("delete connector %s: demoted %d shield-bound resource(s) to unprotected", id, demoted)
	}

	// Deleting a connector changes the compiled ACL (its shields and their
	// resources are gone). RevokeConnector already notified; this path did not, so
	// the cached snapshot kept referencing a connector that no longer exists.
	if r.PolicyNotifier != nil {
		if err := r.PolicyNotifier.NotifyPolicyChange(ctx, tc.TenantID); err != nil {
			return false, fmt.Errorf("delete connector: notify policy change: %w", err)
		}
	}

	return true, nil
}

// RemoteNetworks is the resolver for the remoteNetworks field.
func (r *queryResolver) RemoteNetworks(ctx context.Context) ([]*graph.RemoteNetwork, error) {
	tc := tenant.MustGet(ctx)

	rows, err := r.TenantDB.Query(ctx,
		`SELECT id, name, location, status, created_at
		   FROM remote_networks
		  WHERE tenant_id = $1
		    AND status = 'active'
		  ORDER BY created_at DESC`,
		tc.TenantID,
	)
	if err != nil {
		return nil, fmt.Errorf("remote networks: %w", err)
	}
	defer rows.Close()

	var networks []*graph.RemoteNetwork
	networkIdx := map[string]int{}
	for rows.Next() {
		rn, err := scanRemoteNetwork(rows)
		if err != nil {
			return nil, fmt.Errorf("remote networks: scan: %w", err)
		}
		networkIdx[rn.ID] = len(networks)
		networks = append(networks, rn)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("remote networks: rows: %w", err)
	}
	if networks == nil {
		return []*graph.RemoteNetwork{}, nil
	}

	// Batch-load all connectors for all networks in a single query.
	networkIDs := make([]string, len(networks))
	for i, n := range networks {
		networkIDs[i] = n.ID
	}
	cRows, err := r.TenantDB.Query(ctx,
		`SELECT id, name, status, remote_network_id,
		        last_heartbeat_at, version, hostname, public_ip, lan_addr,
		        cert_not_after, created_at
		   FROM connectors
		  WHERE remote_network_id = ANY($1)
		    AND tenant_id = $2
		  ORDER BY created_at DESC`,
		networkIDs, tc.TenantID,
	)
	if err != nil {
		return nil, fmt.Errorf("remote networks: load connectors: %w", err)
	}
	defer cRows.Close()

	for cRows.Next() {
		c, err := scanConnector(cRows)
		if err != nil {
			return nil, fmt.Errorf("remote networks: scan connector: %w", err)
		}
		if idx, ok := networkIdx[c.RemoteNetworkID]; ok {
			networks[idx].Connectors = append(networks[idx].Connectors, c)
		}
	}
	if err := cRows.Err(); err != nil {
		return nil, fmt.Errorf("remote networks: connector rows: %w", err)
	}

	// Batch-load shields for all networks.
	sRows, err := r.TenantDB.Query(ctx,
		`SELECT id, name, status, remote_network_id, connector_id,
		        last_heartbeat_at, version, hostname, public_ip,
		        interface_addr, cert_not_after, created_at
		   FROM shields
		  WHERE remote_network_id = ANY($1)
		    AND tenant_id = $2
		  ORDER BY created_at DESC`,
		networkIDs, tc.TenantID,
	)
	if err != nil {
		return nil, fmt.Errorf("remote networks: load shields: %w", err)
	}
	defer sRows.Close()

	for sRows.Next() {
		sh, err := scanShield(sRows)
		if err != nil {
			return nil, fmt.Errorf("remote networks: scan shield: %w", err)
		}
		if idx, ok := networkIdx[sh.RemoteNetworkID]; ok {
			networks[idx].Shields = append(networks[idx].Shields, sh)
		}
	}
	if err := sRows.Err(); err != nil {
		return nil, fmt.Errorf("remote networks: shield rows: %w", err)
	}

	for _, n := range networks {
		n.NetworkHealth = computeNetworkHealth(n.Connectors)
	}

	return networks, nil
}

// RemoteNetwork is the resolver for the remoteNetwork field.
func (r *queryResolver) RemoteNetwork(ctx context.Context, id string) (*graph.RemoteNetwork, error) {
	tc := tenant.MustGet(ctx)

	rn, err := scanRemoteNetwork(r.TenantDB.QueryRow(ctx,
		`SELECT id, name, location, status, created_at
		   FROM remote_networks
		  WHERE id = $1
		    AND tenant_id = $2
		    AND status = 'active'`,
		id, tc.TenantID,
	))
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, nil
		}
		return nil, fmt.Errorf("remote network: %w", err)
	}

	connectors, err := r.loadConnectors(ctx, tc.TenantID, id)
	if err != nil {
		return nil, fmt.Errorf("remote network: load connectors: %w", err)
	}
	rn.Connectors = connectors
	rn.NetworkHealth = computeNetworkHealth(connectors)

	shields, err := r.loadShields(ctx, tc.TenantID, id)
	if err != nil {
		return nil, fmt.Errorf("remote network: load shields: %w", err)
	}
	rn.Shields = shields

	return rn, nil
}

// Connectors is the resolver for the connectors field.
func (r *queryResolver) Connectors(ctx context.Context, remoteNetworkID string) ([]*graph.Connector, error) {
	tc := tenant.MustGet(ctx)

	connectors, err := r.loadConnectors(ctx, tc.TenantID, remoteNetworkID)
	if err != nil {
		return nil, fmt.Errorf("connectors: %w", err)
	}

	return connectors, nil
}

// Connector is the resolver for the connector field.
func (r *queryResolver) Connector(ctx context.Context, id string) (*graph.Connector, error) {
	tc := tenant.MustGet(ctx)

	c, err := scanConnector(r.TenantDB.QueryRow(ctx,
		`SELECT id, name, status, remote_network_id,
		        last_heartbeat_at, version, hostname, public_ip, lan_addr,
		        cert_not_after, created_at
		   FROM connectors
		  WHERE id = $1
		    AND tenant_id = $2`,
		id, tc.TenantID,
	))
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, nil
		}
		return nil, fmt.Errorf("connector: %w", err)
	}

	return c, nil
}
