package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"errors"
	"fmt"
	"strings"

	pgx "github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/yourorg/ztna/controller/graph"
	"github.com/yourorg/ztna/controller/internal/apperr"
	"github.com/yourorg/ztna/controller/internal/tenant"
)

// CreateRemoteNetwork is the resolver for the createRemoteNetwork field.
func (r *mutationResolver) CreateRemoteNetwork(ctx context.Context, name string, location graph.NetworkLocation) (*graph.RemoteNetwork, error) {
	tc := tenant.MustGet(ctx)

	rn, err := scanRemoteNetwork(r.TenantDB.QueryRow(ctx,
		`INSERT INTO remote_networks (tenant_id, name, location)
		 VALUES ($1, $2, $3)
		 RETURNING id, name, location, status, created_at`,
		tc.TenantID, name, strings.ToLower(string(location)),
	))
	if err != nil {
		return nil, fmt.Errorf("create remote network: %w", err)
	}

	return rn, nil
}

// DeleteRemoteNetwork is the resolver for the deleteRemoteNetwork field.
func (r *mutationResolver) DeleteRemoteNetwork(ctx context.Context, id string) (bool, error) {
	tc := tenant.MustGet(ctx)

	var discardedID string
	err := r.TenantDB.QueryRow(ctx,
		`UPDATE remote_networks
		    SET status = 'deleted', updated_at = NOW()
		  WHERE id = $1
		    AND tenant_id = $2
		    AND status = 'active'
		    AND NOT EXISTS (
		        SELECT 1 FROM connectors
		         WHERE remote_network_id = $1
		           AND tenant_id = $2
		           AND status NOT IN ('pending', 'revoked')
		    )
		 RETURNING id`,
		id, tc.TenantID,
	).Scan(&discardedID)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return false, fmt.Errorf("delete remote network: network not found, already deleted, or has active connectors")
		}
		return false, fmt.Errorf("delete remote network: %w", err)
	}

	return true, nil
}

// GenerateConnectorToken is the resolver for the generateConnectorToken field.
func (r *mutationResolver) GenerateConnectorToken(ctx context.Context, remoteNetworkID string, connectorName string) (*graph.ConnectorToken, error) {
	tc := tenant.MustGet(ctx)

	name, vErr := validateAgentName("connector", connectorName)
	if vErr != nil {
		return nil, vErr
	}

	var rnStatus string
	err := r.TenantDB.QueryRow(ctx,
		`SELECT status FROM remote_networks WHERE id = $1 AND tenant_id = $2`,
		remoteNetworkID, tc.TenantID,
	).Scan(&rnStatus)
	if err != nil {
		return nil, apperr.UserErrorf("remote network not found")
	}
	if rnStatus != "active" {
		return nil, apperr.UserErrorf("remote network is %q, expected active", rnStatus)
	}

	var connectorID string
	err = r.TenantDB.QueryRow(ctx,
		`INSERT INTO connectors (tenant_id, remote_network_id, name)
		 VALUES ($1, $2, $3)
		 RETURNING id`,
		tc.TenantID, remoteNetworkID, name,
	).Scan(&connectorID)
	if err != nil {
		var pgErr *pgconn.PgError
		if errors.As(err, &pgErr) && pgErr.Code == "23505" { // unique_violation
			return nil, apperr.UserErrorf("a connector named %q already exists", name)
		}
		return nil, fmt.Errorf("generate connector token: insert connector: %w", err)
	}

	// Token minting is lazy: the create path only reserves the pending row.
	// The enrollment token (JWT + Redis jti + install command) is issued on
	// demand by the REST endpoint POST /api/connectors/{id}/token when the
	// detail page loads. See ADR-008. This keeps the credential off the
	// GraphQL/Apollo-cache surface and avoids minting a token that's discarded.
	return &graph.ConnectorToken{ConnectorID: connectorID}, nil
}

// RevokeConnector is the resolver for the revokeConnector field.
func (r *mutationResolver) RevokeConnector(ctx context.Context, id string) (bool, error) {
	tc := tenant.MustGet(ctx)

	var discardedID string
	err := r.TenantDB.QueryRow(ctx,
		`UPDATE connectors
		    SET status = 'revoked', updated_at = NOW()
		  WHERE id = $1
		    AND tenant_id = $2
		    AND status IN ('active', 'disconnected')
		 RETURNING id`,
		id, tc.TenantID,
	).Scan(&discardedID)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return false, fmt.Errorf("revoke connector: connector not found or not in revocable status")
		}
		return false, fmt.Errorf("revoke connector: %w", err)
	}

	return true, nil
}

// DeleteConnector is the resolver for the deleteConnector field.
func (r *mutationResolver) DeleteConnector(ctx context.Context, id string) (bool, error) {
	tc := tenant.MustGet(ctx)

	var discardedID string
	err := r.TenantDB.QueryRow(ctx,
		`DELETE FROM connectors
		  WHERE id = $1
		    AND tenant_id = $2
		    AND status IN ('pending', 'revoked')
		 RETURNING id`,
		id, tc.TenantID,
	).Scan(&discardedID)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return false, fmt.Errorf("delete connector: connector not found or must be revoked before deletion")
		}
		return false, fmt.Errorf("delete connector: %w", err)
	}

	return true, nil
}

// RemoteNetworks is the resolver for the remoteNetworks field.
func (r *queryResolver) RemoteNetworks(ctx context.Context) ([]*graph.RemoteNetwork, error) {
	tc := tenant.MustGet(ctx)

	rows, err := r.TenantDB.Query(ctx,
		`SELECT id, name, location, status, created_at
		   FROM remote_networks
		  WHERE tenant_id = $1
		    AND status = 'active'
		  ORDER BY created_at DESC`,
		tc.TenantID,
	)
	if err != nil {
		return nil, fmt.Errorf("remote networks: %w", err)
	}
	defer rows.Close()

	var networks []*graph.RemoteNetwork
	networkIdx := map[string]int{}
	for rows.Next() {
		rn, err := scanRemoteNetwork(rows)
		if err != nil {
			return nil, fmt.Errorf("remote networks: scan: %w", err)
		}
		networkIdx[rn.ID] = len(networks)
		networks = append(networks, rn)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("remote networks: rows: %w", err)
	}
	if networks == nil {
		return []*graph.RemoteNetwork{}, nil
	}

	// Batch-load all connectors for all networks in a single query.
	networkIDs := make([]string, len(networks))
	for i, n := range networks {
		networkIDs[i] = n.ID
	}
	cRows, err := r.TenantDB.Query(ctx,
		`SELECT id, name, status, remote_network_id,
		        last_heartbeat_at, version, hostname, public_ip, lan_addr,
		        cert_not_after, created_at
		   FROM connectors
		  WHERE remote_network_id = ANY($1)
		    AND tenant_id = $2
		  ORDER BY created_at DESC`,
		networkIDs, tc.TenantID,
	)
	if err != nil {
		return nil, fmt.Errorf("remote networks: load connectors: %w", err)
	}
	defer cRows.Close()

	for cRows.Next() {
		c, err := scanConnector(cRows)
		if err != nil {
			return nil, fmt.Errorf("remote networks: scan connector: %w", err)
		}
		if idx, ok := networkIdx[c.RemoteNetworkID]; ok {
			networks[idx].Connectors = append(networks[idx].Connectors, c)
		}
	}
	if err := cRows.Err(); err != nil {
		return nil, fmt.Errorf("remote networks: connector rows: %w", err)
	}

	// Batch-load shields for all networks.
	sRows, err := r.TenantDB.Query(ctx,
		`SELECT id, name, status, remote_network_id, connector_id,
		        last_heartbeat_at, version, hostname, public_ip,
		        interface_addr, cert_not_after, created_at
		   FROM shields
		  WHERE remote_network_id = ANY($1)
		    AND tenant_id = $2
		  ORDER BY created_at DESC`,
		networkIDs, tc.TenantID,
	)
	if err != nil {
		return nil, fmt.Errorf("remote networks: load shields: %w", err)
	}
	defer sRows.Close()

	for sRows.Next() {
		sh, err := scanShield(sRows)
		if err != nil {
			return nil, fmt.Errorf("remote networks: scan shield: %w", err)
		}
		if idx, ok := networkIdx[sh.RemoteNetworkID]; ok {
			networks[idx].Shields = append(networks[idx].Shields, sh)
		}
	}
	if err := sRows.Err(); err != nil {
		return nil, fmt.Errorf("remote networks: shield rows: %w", err)
	}

	for _, n := range networks {
		n.NetworkHealth = computeNetworkHealth(n.Connectors)
	}

	return networks, nil
}

// RemoteNetwork is the resolver for the remoteNetwork field.
func (r *queryResolver) RemoteNetwork(ctx context.Context, id string) (*graph.RemoteNetwork, error) {
	tc := tenant.MustGet(ctx)

	rn, err := scanRemoteNetwork(r.TenantDB.QueryRow(ctx,
		`SELECT id, name, location, status, created_at
		   FROM remote_networks
		  WHERE id = $1
		    AND tenant_id = $2
		    AND status = 'active'`,
		id, tc.TenantID,
	))
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, nil
		}
		return nil, fmt.Errorf("remote network: %w", err)
	}

	connectors, err := r.loadConnectors(ctx, tc.TenantID, id)
	if err != nil {
		return nil, fmt.Errorf("remote network: load connectors: %w", err)
	}
	rn.Connectors = connectors
	rn.NetworkHealth = computeNetworkHealth(connectors)

	shields, err := r.loadShields(ctx, tc.TenantID, id)
	if err != nil {
		return nil, fmt.Errorf("remote network: load shields: %w", err)
	}
	rn.Shields = shields

	return rn, nil
}

// Connectors is the resolver for the connectors field.
func (r *queryResolver) Connectors(ctx context.Context, remoteNetworkID string) ([]*graph.Connector, error) {
	tc := tenant.MustGet(ctx)

	connectors, err := r.loadConnectors(ctx, tc.TenantID, remoteNetworkID)
	if err != nil {
		return nil, fmt.Errorf("connectors: %w", err)
	}

	return connectors, nil
}

// Connector is the resolver for the connector field.
func (r *queryResolver) Connector(ctx context.Context, id string) (*graph.Connector, error) {
	tc := tenant.MustGet(ctx)

	c, err := scanConnector(r.TenantDB.QueryRow(ctx,
		`SELECT id, name, status, remote_network_id,
		        last_heartbeat_at, version, hostname, public_ip, lan_addr,
		        cert_not_after, created_at
		   FROM connectors
		  WHERE id = $1
		    AND tenant_id = $2`,
		id, tc.TenantID,
	))
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, nil
		}
		return nil, fmt.Errorf("connector: %w", err)
	}

	return c, nil
}
