package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"fmt"

	"github.com/yourorg/ztna/controller/graph"
)

// PromoteDiscoveredService is the resolver for the promoteDiscoveredService field.
func (r *mutationResolver) PromoteDiscoveredService(ctx context.Context, shieldID string, protocol string, port int) (*graph.Resource, error) {
	panic(fmt.Errorf("not implemented: PromoteDiscoveredService - promoteDiscoveredService"))
}

// TriggerScan is the resolver for the triggerScan field.
func (r *mutationResolver) TriggerScan(ctx context.Context, connectorID string, targets []string, ports []int) (string, error) {
	panic(fmt.Errorf("not implemented: TriggerScan - triggerScan"))
}

// GetDiscoveredServices is the resolver for the getDiscoveredServices field.
func (r *queryResolver) GetDiscoveredServices(ctx context.Context, shieldID string) ([]*graph.DiscoveredService, error) {
	panic(fmt.Errorf("not implemented: GetDiscoveredServices - getDiscoveredServices"))
}

// GetScanResults is the resolver for the getScanResults field.
func (r *queryResolver) GetScanResults(ctx context.Context, requestID string) ([]*graph.ScanResult, error) {
	panic(fmt.Errorf("not implemented: GetScanResults - getScanResults"))
}
