package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/yourorg/ztna/controller/graph"
	"github.com/yourorg/ztna/controller/internal/audit"
	"github.com/yourorg/ztna/controller/internal/auth/providers"
	"github.com/yourorg/ztna/controller/internal/idp"
	"github.com/yourorg/ztna/controller/internal/permission"
	"github.com/yourorg/ztna/controller/internal/scim"
	"github.com/yourorg/ztna/controller/internal/tenant"
)

// CreateIdpConnection is the resolver for the createIdpConnection field.
func (r *mutationResolver) CreateIdpConnection(ctx context.Context, input graph.CreateIdpConnectionInput) (*graph.WorkspaceIdpConnection, error) {
	tc := tenant.MustGet(ctx)

	created, err := r.IdpStore.CreateWorkspaceConnection(ctx, tc.TenantID, idp.CreateInput{
		Provider:     input.Provider,
		DisplayName:  input.DisplayName,
		Issuer:       input.Issuer,
		ClientID:     input.ClientID,
		ClientSecret: input.ClientSecret,
		DiscoveryURL: deref(input.DiscoveryURL),
		Scopes:       deref(input.Scopes),
		DomainHint:   deref(input.DomainHint),
	})
	if err != nil {
		return nil, fmt.Errorf("createIdpConnection: %w", err)
	}
	r.auditIdp(ctx, tc, "idp.connection.create", created.ID, map[string]any{
		"provider": created.Provider, "issuer": created.Issuer,
	})
	return idpConnToGQL(*created), nil
}

// UpdateIdpConnection is the resolver for the updateIdpConnection field.
func (r *mutationResolver) UpdateIdpConnection(ctx context.Context, id string, input graph.UpdateIdpConnectionInput) (*graph.WorkspaceIdpConnection, error) {
	tc := tenant.MustGet(ctx)

	updated, err := r.IdpStore.UpdateWorkspaceConnection(ctx, tc.TenantID, id, idp.UpdateInput{
		DisplayName:  input.DisplayName,
		ClientID:     input.ClientID,
		ClientSecret: input.ClientSecret,
		DiscoveryURL: input.DiscoveryURL,
		Scopes:       input.Scopes,
		DomainHint:   input.DomainHint,
	})
	if errors.Is(err, idp.ErrConnectionNotFound) {
		return nil, fmt.Errorf("updateIdpConnection: connection not found")
	}
	if err != nil {
		return nil, fmt.Errorf("updateIdpConnection: %w", err)
	}
	r.auditIdp(ctx, tc, "idp.connection.update", id, map[string]any{
		"secret_rotated": input.ClientSecret != nil,
	})
	return idpConnToGQL(*updated), nil
}

// SetIdpConnectionStatus is the resolver for the setIdpConnectionStatus field.
func (r *mutationResolver) SetIdpConnectionStatus(ctx context.Context, id string, status string) (*graph.WorkspaceIdpConnection, error) {
	tc := tenant.MustGet(ctx)
	if status != "active" && status != "disabled" {
		return nil, fmt.Errorf("setIdpConnectionStatus: status must be 'active' or 'disabled'")
	}

	// Disabling removes a login path — guard against locking the workspace out.
	if status == "disabled" {
		if err := r.guardLastLoginPath(ctx, tc); err != nil {
			return nil, err
		}
	}

	if err := r.IdpStore.SetStatus(ctx, tc.TenantID, id, status); err != nil {
		if errors.Is(err, idp.ErrConnectionNotFound) {
			return nil, fmt.Errorf("setIdpConnectionStatus: connection not found")
		}
		return nil, fmt.Errorf("setIdpConnectionStatus: %w", err)
	}

	action := "idp.connection.enable"
	if status == "disabled" {
		action = "idp.connection.disable"
	}
	r.auditIdp(ctx, tc, action, id, nil)

	// A disabled connection is no longer a valid login path: revoke the sessions
	// of everyone who authenticates through it.
	if status == "disabled" {
		r.revokeConnectionSessions(ctx, tc, id)
	}

	conn, err := r.IdpStore.GetByID(ctx, id)
	if err != nil {
		return nil, fmt.Errorf("setIdpConnectionStatus reload: %w", err)
	}
	return idpConnToGQL(*conn), nil
}

// DeleteIdpConnection is the resolver for the deleteIdpConnection field.
func (r *mutationResolver) DeleteIdpConnection(ctx context.Context, id string) (bool, error) {
	tc := tenant.MustGet(ctx)

	// Snapshot affected users BEFORE the delete: external_identities cascades on
	// connection delete, so after it the link rows are gone.
	userIDs, err := r.IdpStore.UserIDsForConnection(ctx, tc.TenantID, id)
	if err != nil {
		return false, fmt.Errorf("deleteIdpConnection: %w", err)
	}

	if err := r.guardLastLoginPath(ctx, tc); err != nil {
		return false, err
	}

	if err := r.IdpStore.DeleteWorkspaceConnection(ctx, tc.TenantID, id); err != nil {
		if errors.Is(err, idp.ErrConnectionNotFound) {
			return false, fmt.Errorf("deleteIdpConnection: connection not found")
		}
		return false, fmt.Errorf("deleteIdpConnection: %w", err)
	}
	r.auditIdp(ctx, tc, "idp.connection.delete", id, nil)

	// Revoke sessions of everyone whose login path we just removed.
	r.bumpUsers(ctx, tc, userIDs)
	return true, nil
}

// TestIdpConnection is the resolver for the testIdpConnection field.
//
// Phase 4 scope (ADR-025 §3.1): it runs the achievable active checks —
// OIDC discovery reachability AND the per-connection mapping-configuration
// validation — and returns the fail-closed mapping state. It deliberately does
// NOT claim the mapping is "proven": the real POST→GET→verify→DELETE probe-user
// round-trip requires the SCIM /Users endpoint, which lands in Phase 5. Until
// that probe runs, SCIM stays disabled unless an identity.mapping.break_glass
// override is in effect.
func (r *mutationResolver) TestIdpConnection(ctx context.Context, id string) (*graph.IdpTestResult, error) {
	tc := tenant.MustGet(ctx)

	conn, err := r.IdpStore.GetByID(ctx, id)
	if err != nil {
		if errors.Is(err, idp.ErrConnectionNotFound) {
			return nil, fmt.Errorf("testIdpConnection: connection not found")
		}
		return nil, fmt.Errorf("testIdpConnection: %w", err)
	}
	// Tenant guard: only test your own connection (GetByID is not tenant-scoped).
	if conn.TenantID == nil || *conn.TenantID != tc.TenantID {
		return nil, fmt.Errorf("testIdpConnection: connection not found")
	}

	// 1. OIDC discovery probe (issuer reachability + required endpoints).
	p := providers.NewOIDCProvider(conn.Provider, conn.Issuer, conn.ClientID, "", conn.DiscoveryURL, conn.Scopes)
	issuer, perr := p.Probe(ctx)
	if perr != nil {
		msg := perr.Error()
		reason := "OIDC discovery failed: " + msg
		return &graph.IdpTestResult{
			Ok:                 false,
			Message:            &msg,
			MappingState:       string(scim.MappingUnproven),
			ScimEnabledAllowed: false,
			Reason:             &reason,
		}, nil
	}

	// 2. Mapping-config validation (fail-closed). The gate never reports
	// "proven" without a real round-trip (RoundTripVerified stays false in
	// Phase 4), so ScimEnabledAllowed is false unless an override applies.
	gate := scim.NewMappingGate(conn.Provider)
	res, err := gate.Evaluate(ctx, conn.SubjectClaim, conn.ScimIdentifier, scim.BreakGlassOverride{})
	if err != nil {
		return nil, fmt.Errorf("testIdpConnection mapping gate: %w", err)
	}

	// Keep SCIM disabled (fail-closed): the gate's evaluation never enables
	// SCIM without proof or an override. We persist the disabled state so a
	// re-enable can only follow a proven mapping or a break-glass override.
	if err := r.IdpStore.SetSCIMEnabled(ctx, tc.TenantID, id, res.ScimEnabledAllowed); err != nil {
		return nil, fmt.Errorf("testIdpConnection set scim_enabled: %w", err)
	}

	return &graph.IdpTestResult{
		Ok:                 true,
		Issuer:             &issuer,
		MappingState:       string(res.MappingState),
		ScimEnabledAllowed: res.ScimEnabledAllowed,
		Reason:             &res.Reason,
	}, nil
}

// SetPlatformLoginEnabled is the resolver for the setPlatformLoginEnabled field.
func (r *mutationResolver) SetPlatformLoginEnabled(ctx context.Context, enabled bool) (bool, error) {
	tc := tenant.MustGet(ctx)

	// No-lockout (ADR-024 §5): disabling platform login is refused when the
	// workspace has no active identity provider of its own, unless the actor is a
	// break-glass admin — otherwise the workspace would strand every member.
	if !enabled {
		n, err := r.IdpStore.CountActiveWorkspaceConnections(ctx, tc.TenantID)
		if err != nil {
			return false, fmt.Errorf("setPlatformLoginEnabled: %w", err)
		}
		if err := platformDisableGuard(n, r.BreakGlassEmails[tc.Email]); err != nil {
			return false, err
		}
	}

	if err := r.IdpStore.SetPlatformLoginEnabled(ctx, tc.TenantID, enabled); err != nil {
		return false, fmt.Errorf("setPlatformLoginEnabled: %w", err)
	}
	action := "idp.platform_login.enable"
	if !enabled {
		action = "idp.platform_login.disable"
	}
	r.auditIdp(ctx, tc, action, tc.TenantID, nil)
	return enabled, nil
}

// MintScimToken is the resolver for the mintScimToken field.
func (r *mutationResolver) MintScimToken(ctx context.Context, connectionID string, label *string, expiresAt *time.Time) (*graph.ScimTokenMintResult, error) {
	tc := tenant.MustGet(ctx)

	if err := r.validateSCIMConnection(ctx, tc.TenantID, connectionID); err != nil {
		return nil, err
	}

	result, err := r.ScimStore.Mint(
		ctx,
		tc.TenantID,
		connectionID,
		label,
		stringPtrOrNil(tc.UserID),
		expiresAt,
	)
	if err != nil {
		return nil, fmt.Errorf("mint SCIM token: %w", err)
	}

	_ = audit.Record(ctx, r.Pool, audit.Entry{
		TenantID:    tc.TenantID,
		ActorUserID: tc.UserID,
		ActorEmail:  tc.Email,
		Action:      "scim.token.mint",
		TargetType:  "scim_token",
		TargetID:    result.Token.ID,
		Details: map[string]any{
			"connection_id": connectionID,
			"label":         label,
			"expires_at":    expiresAt,
		},
	})

	return &graph.ScimTokenMintResult{
		Token:     scimTokenToGQL(result.Token),
		Plaintext: result.Plaintext,
	}, nil
}

// RotateScimToken is the resolver for the rotateScimToken field.
func (r *mutationResolver) RotateScimToken(ctx context.Context, connectionID string, label *string, expiresAt *time.Time) (*graph.ScimTokenMintResult, error) {
	tc := tenant.MustGet(ctx)

	if err := r.validateSCIMConnection(ctx, tc.TenantID, connectionID); err != nil {
		return nil, err
	}

	result, err := r.ScimStore.Rotate(
		ctx,
		tc.TenantID,
		connectionID,
		label,
		stringPtrOrNil(tc.UserID),
		expiresAt,
	)
	if err != nil {
		return nil, fmt.Errorf("rotate SCIM token: %w", err)
	}

	_ = audit.Record(ctx, r.Pool, audit.Entry{
		TenantID:    tc.TenantID,
		ActorUserID: tc.UserID,
		ActorEmail:  tc.Email,
		Action:      "scim.token.rotate",
		TargetType:  "scim_token",
		TargetID:    result.Token.ID,
		Details: map[string]any{
			"connection_id": connectionID,
			"label":         label,
			"expires_at":    expiresAt,
		},
	})

	return &graph.ScimTokenMintResult{
		Token:     scimTokenToGQL(result.Token),
		Plaintext: result.Plaintext,
	}, nil
}

// RevokeScimToken is the resolver for the revokeScimToken field.
func (r *mutationResolver) RevokeScimToken(ctx context.Context, connectionID string, tokenID string) (bool, error) {
	tc := tenant.MustGet(ctx)

	if err := r.validateSCIMConnection(ctx, tc.TenantID, connectionID); err != nil {
		return false, err
	}

	if err := r.ScimStore.Revoke(
		ctx,
		tc.TenantID,
		connectionID,
		tokenID,
	); err != nil {
		return false, fmt.Errorf("revoke SCIM token: %w", err)
	}

	_ = audit.Record(ctx, r.Pool, audit.Entry{
		TenantID:    tc.TenantID,
		ActorUserID: tc.UserID,
		ActorEmail:  tc.Email,
		Action:      "scim.token.revoke",
		TargetType:  "scim_token",
		TargetID:    tokenID,
		Details: map[string]any{
			"connection_id": connectionID,
		},
	})

	return true, nil
}

// GrantPermission is the resolver for the grantPermission field.
//
// The @hasRole(ADMIN) directive gates WHO may call this. Possession of the
// granted permission is a separate, explicit row — granting it to another user
// (admin or not) never widens what ADMIN alone can do: HasPermission always
// answers "does the row exist?".
func (r *mutationResolver) GrantPermission(ctx context.Context, userID string, permission string) (*graph.WorkspacePermission, error) {
	tc := tenant.MustGet(ctx)

	if userID == "" || permission == "" {
		return nil, fmt.Errorf("grantPermission: userId and permission are required")
	}

	if err := r.PermissionStore.Grant(ctx, tc.TenantID, userID, permission, tc.UserID); err != nil {
		return nil, fmt.Errorf("grant permission: %w", err)
	}

	_ = audit.Record(ctx, r.Pool, audit.Entry{
		TenantID:    tc.TenantID,
		ActorUserID: tc.UserID,
		ActorEmail:  tc.Email,
		Action:      "permission.grant",
		TargetType:  "user",
		TargetID:    userID,
		Details: map[string]any{
			"permission": permission,
			"granted_by": tc.UserID,
		},
	})

	return &graph.WorkspacePermission{
		WorkspaceID: tc.TenantID,
		UserID:      userID,
		Permission:  permission,
		GrantedBy:   &tc.UserID,
	}, nil
}

// EnableScimBreakGlass is the resolver for the enableScimBreakGlass field.
//
// It enables SCIM for a connection DESPITE an unproven identity mapping, using
// the dedicated identity.mapping.break_glass permission (ADR-025 §3.2). The
// @hasRole(ADMIN) directive only gates WHO may call this; possession of the
// permission is an EXPLICIT grant checked here — an ADMIN without the row is
// denied. A mandatory reason is required and every invocation is audited as
// scim.mapping.break_glass_override.
func (r *mutationResolver) EnableScimBreakGlass(ctx context.Context, connectionID string, reason string) (bool, error) {
	tc := tenant.MustGet(ctx)

	if reason == "" {
		return false, fmt.Errorf("enableScimBreakGlass: a mandatory reason is required")
	}

	conn, err := r.IdpStore.GetByID(ctx, connectionID)
	if err != nil {
		if errors.Is(err, idp.ErrConnectionNotFound) {
			return false, fmt.Errorf("enableScimBreakGlass: connection not found")
		}
		return false, fmt.Errorf("enableScimBreakGlass: %w", err)
	}
	if conn.TenantID == nil || *conn.TenantID != tc.TenantID {
		return false, fmt.Errorf("enableScimBreakGlass: connection not found")
	}

	// Explicit, authoritative permission check (NOT implied by ADMIN role).
	held, err := r.PermissionStore.HasPermission(ctx, tc.TenantID, tc.UserID, permission.BreakGlassMapping)
	if err != nil {
		return false, fmt.Errorf("enableScimBreakGlass: permission check: %w", err)
	}
	if !held {
		return false, fmt.Errorf("enableScimBreakGlass: requires the %q permission (ADMIN role alone is insufficient)", permission.BreakGlassMapping)
	}

	// Enable SCIM despite the unproven mapping (the override does NOT retroactively
	// make the mapping "proven" — it only permits enabling).
	if err := r.IdpStore.SetSCIMEnabled(ctx, tc.TenantID, connectionID, true); err != nil {
		return false, fmt.Errorf("enableScimBreakGlass: set scim_enabled: %w", err)
	}

	_ = audit.Record(ctx, r.Pool, audit.Entry{
		TenantID:    tc.TenantID,
		ActorUserID: tc.UserID,
		ActorEmail:  tc.Email,
		Action:      "scim.mapping.break_glass_override",
		TargetType:  "idp_connection",
		TargetID:    connectionID,
		Details: map[string]any{
			"permission":          permission.BreakGlassMapping,
			"reason":              reason,
			"mapping_proven":      false,
			"validation_bypassed": true,
		},
	})

	return true, nil
}

// AcceptScimConflict is the resolver for the acceptScimConflict field.
// It requires the explicit identity.mapping.break_glass permission (ADMIN role
// alone is insufficient) and a mandatory reason. The DirectoryService performs
// the atomic link + provisioning_owner transition + audit.
func (r *mutationResolver) AcceptScimConflict(ctx context.Context, connectionID string, canonicalKey string, reason string) (bool, error) {
	tc := tenant.MustGet(ctx)
	if err := r.validateSCIMConnection(ctx, tc.TenantID, connectionID); err != nil {
		return false, err
	}
	ds := r.ScimStore.DirectoryService()
	if ds == nil {
		return false, fmt.Errorf("acceptScimConflict: directory service unavailable")
	}
	serr := ds.AcceptLink(ctx, tc.TenantID, connectionID, tc.UserID, tc.Email, canonicalKey, reason)
	if serr != nil {
		return false, fmt.Errorf("acceptScimConflict: %w", serr)
	}
	return true, nil
}

// RejectScimConflict is the resolver for the rejectScimConflict field.
func (r *mutationResolver) RejectScimConflict(ctx context.Context, connectionID string, canonicalKey string, reason string) (bool, error) {
	tc := tenant.MustGet(ctx)
	if err := r.validateSCIMConnection(ctx, tc.TenantID, connectionID); err != nil {
		return false, err
	}
	ds := r.ScimStore.DirectoryService()
	if ds == nil {
		return false, fmt.Errorf("rejectScimConflict: directory service unavailable")
	}
	serr := ds.Reject(ctx, tc.TenantID, connectionID, tc.UserID, tc.Email, canonicalKey, reason)
	if serr != nil {
		return false, fmt.Errorf("rejectScimConflict: %w", serr)
	}
	return true, nil
}

// ReopenScimConflict is the resolver for the reopenScimConflict field.
func (r *mutationResolver) ReopenScimConflict(ctx context.Context, connectionID string, canonicalKey string, reason string) (bool, error) {
	tc := tenant.MustGet(ctx)
	if err := r.validateSCIMConnection(ctx, tc.TenantID, connectionID); err != nil {
		return false, err
	}
	ds := r.ScimStore.DirectoryService()
	if ds == nil {
		return false, fmt.Errorf("reopenScimConflict: directory service unavailable")
	}
	serr := ds.Reopen(ctx, tc.TenantID, connectionID, tc.UserID, tc.Email, canonicalKey, reason)
	if serr != nil {
		return false, fmt.Errorf("reopenScimConflict: %w", serr)
	}
	return true, nil
}

// IdpConnections is the resolver for the idpConnections field.
func (r *queryResolver) IdpConnections(ctx context.Context) ([]*graph.WorkspaceIdpConnection, error) {
	tc := tenant.MustGet(ctx)

	conns, err := r.IdpStore.ListWorkspaceConnections(ctx, tc.TenantID)
	if err != nil {
		return nil, fmt.Errorf("idpConnections: %w", err)
	}
	out := make([]*graph.WorkspaceIdpConnection, 0, len(conns))
	for _, c := range conns {
		out = append(out, idpConnToGQL(c))
	}
	return out, nil
}

// PlatformLoginEnabled is the resolver for the platformLoginEnabled field.
func (r *queryResolver) PlatformLoginEnabled(ctx context.Context) (bool, error) {
	tc := tenant.MustGet(ctx)

	enabled, err := r.IdpStore.PlatformLoginEnabled(ctx, tc.TenantID)
	if err != nil {
		return false, fmt.Errorf("platformLoginEnabled: %w", err)
	}
	return enabled, nil
}

// ScimTokens is the resolver for the scimTokens field.
func (r *queryResolver) ScimTokens(ctx context.Context, connectionID string) ([]*graph.ScimToken, error) {
	tc := tenant.MustGet(ctx)

	if err := r.validateSCIMConnection(ctx, tc.TenantID, connectionID); err != nil {
		return nil, err
	}

	tokens, err := r.ScimStore.List(
		ctx,
		tc.TenantID,
		connectionID,
	)
	if err != nil {
		return nil, fmt.Errorf("list SCIM tokens: %w", err)
	}

	out := make([]*graph.ScimToken, 0, len(tokens))
	for _, token := range tokens {
		out = append(out, scimTokenToGQL(token))
	}

	return out, nil
}

// ScimConflicts is the resolver for the scimConflicts field.
func (r *queryResolver) ScimConflicts(ctx context.Context, connectionID string) ([]*graph.ScimConflict, error) {
	tc := tenant.MustGet(ctx)
	if err := r.validateSCIMConnection(ctx, tc.TenantID, connectionID); err != nil {
		return nil, err
	}
	ds := r.ScimStore.DirectoryService()
	if ds == nil {
		return nil, fmt.Errorf("scimConflicts: directory service unavailable")
	}
	recs, err := ds.ListConflicts(ctx, tc.TenantID, connectionID)
	if err != nil {
		return nil, fmt.Errorf("scimConflicts: %w", err)
	}
	out := make([]*graph.ScimConflict, 0, len(recs))
	for i := range recs {
		out = append(out, conflictToGQL(&recs[i]))
	}
	return out, nil
}
