package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"errors"
	"fmt"

	"github.com/yourorg/ztna/controller/graph"
	"github.com/yourorg/ztna/controller/internal/auth/providers"
	"github.com/yourorg/ztna/controller/internal/idp"
	"github.com/yourorg/ztna/controller/internal/tenant"
)

// CreateIdpConnection is the resolver for the createIdpConnection field.
func (r *mutationResolver) CreateIdpConnection(ctx context.Context, input graph.CreateIdpConnectionInput) (*graph.WorkspaceIdpConnection, error) {
	tc := tenant.MustGet(ctx)

	created, err := r.IdpStore.CreateWorkspaceConnection(ctx, tc.TenantID, idp.CreateInput{
		Provider:     input.Provider,
		DisplayName:  input.DisplayName,
		Issuer:       input.Issuer,
		ClientID:     input.ClientID,
		ClientSecret: input.ClientSecret,
		DiscoveryURL: deref(input.DiscoveryURL),
		Scopes:       deref(input.Scopes),
		DomainHint:   deref(input.DomainHint),
	})
	if err != nil {
		return nil, fmt.Errorf("createIdpConnection: %w", err)
	}
	r.auditIdp(ctx, tc, "idp.connection.create", created.ID, map[string]any{
		"provider": created.Provider, "issuer": created.Issuer,
	})
	return idpConnToGQL(*created), nil
}

// UpdateIdpConnection is the resolver for the updateIdpConnection field.
func (r *mutationResolver) UpdateIdpConnection(ctx context.Context, id string, input graph.UpdateIdpConnectionInput) (*graph.WorkspaceIdpConnection, error) {
	tc := tenant.MustGet(ctx)

	updated, err := r.IdpStore.UpdateWorkspaceConnection(ctx, tc.TenantID, id, idp.UpdateInput{
		DisplayName:  input.DisplayName,
		ClientID:     input.ClientID,
		ClientSecret: input.ClientSecret,
		DiscoveryURL: input.DiscoveryURL,
		Scopes:       input.Scopes,
		DomainHint:   input.DomainHint,
	})
	if errors.Is(err, idp.ErrConnectionNotFound) {
		return nil, fmt.Errorf("updateIdpConnection: connection not found")
	}
	if err != nil {
		return nil, fmt.Errorf("updateIdpConnection: %w", err)
	}
	r.auditIdp(ctx, tc, "idp.connection.update", id, map[string]any{
		"secret_rotated": input.ClientSecret != nil,
	})
	return idpConnToGQL(*updated), nil
}

// SetIdpConnectionStatus is the resolver for the setIdpConnectionStatus field.
func (r *mutationResolver) SetIdpConnectionStatus(ctx context.Context, id string, status string) (*graph.WorkspaceIdpConnection, error) {
	tc := tenant.MustGet(ctx)
	if status != "active" && status != "disabled" {
		return nil, fmt.Errorf("setIdpConnectionStatus: status must be 'active' or 'disabled'")
	}

	// Disabling removes a login path — guard against locking the workspace out.
	if status == "disabled" {
		if err := r.guardLastLoginPath(ctx, tc); err != nil {
			return nil, err
		}
	}

	if err := r.IdpStore.SetStatus(ctx, tc.TenantID, id, status); err != nil {
		if errors.Is(err, idp.ErrConnectionNotFound) {
			return nil, fmt.Errorf("setIdpConnectionStatus: connection not found")
		}
		return nil, fmt.Errorf("setIdpConnectionStatus: %w", err)
	}

	action := "idp.connection.enable"
	if status == "disabled" {
		action = "idp.connection.disable"
	}
	r.auditIdp(ctx, tc, action, id, nil)

	// A disabled connection is no longer a valid login path: revoke the sessions
	// of everyone who authenticates through it.
	if status == "disabled" {
		r.revokeConnectionSessions(ctx, tc, id)
	}

	conn, err := r.IdpStore.GetByID(ctx, id)
	if err != nil {
		return nil, fmt.Errorf("setIdpConnectionStatus reload: %w", err)
	}
	return idpConnToGQL(*conn), nil
}

// DeleteIdpConnection is the resolver for the deleteIdpConnection field.
func (r *mutationResolver) DeleteIdpConnection(ctx context.Context, id string) (bool, error) {
	tc := tenant.MustGet(ctx)

	// Snapshot affected users BEFORE the delete: external_identities cascades on
	// connection delete, so after it the link rows are gone.
	userIDs, err := r.IdpStore.UserIDsForConnection(ctx, tc.TenantID, id)
	if err != nil {
		return false, fmt.Errorf("deleteIdpConnection: %w", err)
	}

	if err := r.guardLastLoginPath(ctx, tc); err != nil {
		return false, err
	}

	if err := r.IdpStore.DeleteWorkspaceConnection(ctx, tc.TenantID, id); err != nil {
		if errors.Is(err, idp.ErrConnectionNotFound) {
			return false, fmt.Errorf("deleteIdpConnection: connection not found")
		}
		return false, fmt.Errorf("deleteIdpConnection: %w", err)
	}
	r.auditIdp(ctx, tc, "idp.connection.delete", id, nil)

	// Revoke sessions of everyone whose login path we just removed.
	r.bumpUsers(ctx, tc, userIDs)
	return true, nil
}

// TestIdpConnection is the resolver for the testIdpConnection field.
func (r *mutationResolver) TestIdpConnection(ctx context.Context, id string) (*graph.IdpTestResult, error) {
	tc := tenant.MustGet(ctx)

	conn, err := r.IdpStore.GetByID(ctx, id)
	if err != nil {
		if errors.Is(err, idp.ErrConnectionNotFound) {
			return nil, fmt.Errorf("testIdpConnection: connection not found")
		}
		return nil, fmt.Errorf("testIdpConnection: %w", err)
	}
	// Tenant guard: only test your own connection (GetByID is not tenant-scoped).
	if conn.TenantID == nil || *conn.TenantID != tc.TenantID {
		return nil, fmt.Errorf("testIdpConnection: connection not found")
	}

	// Reuse the real OIDC discovery (issuer match + required endpoints) without a
	// full login. The secret is not needed to probe discovery.
	p := providers.NewOIDCProvider(conn.Provider, conn.Issuer, conn.ClientID, "", conn.DiscoveryURL, conn.Scopes)
	issuer, perr := p.Probe(ctx)
	if perr != nil {
		msg := perr.Error()
		return &graph.IdpTestResult{Ok: false, Message: &msg}, nil
	}
	return &graph.IdpTestResult{Ok: true, Issuer: &issuer}, nil
}

// SetPlatformLoginEnabled is the resolver for the setPlatformLoginEnabled field.
func (r *mutationResolver) SetPlatformLoginEnabled(ctx context.Context, enabled bool) (bool, error) {
	tc := tenant.MustGet(ctx)

	// No-lockout (ADR-024 §5): disabling platform login is refused when the
	// workspace has no active identity provider of its own, unless the actor is a
	// break-glass admin — otherwise the workspace would strand every member.
	if !enabled {
		n, err := r.IdpStore.CountActiveWorkspaceConnections(ctx, tc.TenantID)
		if err != nil {
			return false, fmt.Errorf("setPlatformLoginEnabled: %w", err)
		}
		if err := platformDisableGuard(n, r.BreakGlassEmails[tc.Email]); err != nil {
			return false, err
		}
	}

	if err := r.IdpStore.SetPlatformLoginEnabled(ctx, tc.TenantID, enabled); err != nil {
		return false, fmt.Errorf("setPlatformLoginEnabled: %w", err)
	}
	action := "idp.platform_login.enable"
	if !enabled {
		action = "idp.platform_login.disable"
	}
	r.auditIdp(ctx, tc, action, tc.TenantID, nil)
	return enabled, nil
}

// IdpConnections is the resolver for the idpConnections field.
func (r *queryResolver) IdpConnections(ctx context.Context) ([]*graph.WorkspaceIdpConnection, error) {
	tc := tenant.MustGet(ctx)

	conns, err := r.IdpStore.ListWorkspaceConnections(ctx, tc.TenantID)
	if err != nil {
		return nil, fmt.Errorf("idpConnections: %w", err)
	}
	out := make([]*graph.WorkspaceIdpConnection, 0, len(conns))
	for _, c := range conns {
		out = append(out, idpConnToGQL(c))
	}
	return out, nil
}

// PlatformLoginEnabled is the resolver for the platformLoginEnabled field.
func (r *queryResolver) PlatformLoginEnabled(ctx context.Context) (bool, error) {
	tc := tenant.MustGet(ctx)

	enabled, err := r.IdpStore.PlatformLoginEnabled(ctx, tc.TenantID)
	if err != nil {
		return false, fmt.Errorf("platformLoginEnabled: %w", err)
	}
	return enabled, nil
}
