package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"
	"time"

	"github.com/yourorg/ztna/controller/graph"
	"github.com/yourorg/ztna/controller/internal/tenant"
)

// ConnectorLogs is the resolver for the connectorLogs field.
func (r *queryResolver) ConnectorLogs(ctx context.Context, limit *int) ([]*graph.ConnectorLog, error) {
	tc, ok := tenant.Get(ctx)
	if !ok {
		return nil, fmt.Errorf("unauthenticated")
	}
	if tc.Role != "admin" {
		return nil, fmt.Errorf("forbidden: only admins can view connector logs")
	}

	n := 100
	if limit != nil && *limit > 0 {
		n = *limit
	}

	rows, err := r.Pool.Query(ctx,
		`SELECT id, workspace_id, connector_id, message, created_at
		   FROM connector_logs
		  WHERE workspace_id = $1
		  ORDER BY created_at DESC
		  LIMIT $2`,
		tc.TenantID, n,
	)
	if err != nil {
		return nil, fmt.Errorf("query connector logs: %w", err)
	}
	defer rows.Close()

	var logs []*graph.ConnectorLog
	for rows.Next() {
		var (
			id, workspaceID, connectorID, message string
			createdAt                             time.Time
		)
		if err := rows.Scan(&id, &workspaceID, &connectorID, &message, &createdAt); err != nil {
			return nil, fmt.Errorf("scan connector log: %w", err)
		}
		logs = append(logs, &graph.ConnectorLog{
			ID:          id,
			WorkspaceID: workspaceID,
			ConnectorID: connectorID,
			Message:     message,
			CreatedAt:   createdAt.UTC().Format(time.RFC3339),
		})
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("iterate connector logs: %w", err)
	}

	return logs, nil
}
