package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"fmt"

	"github.com/yourorg/ztna/controller/graph"
)

// CreateGroup is the resolver for the createGroup field.
func (r *mutationResolver) CreateGroup(ctx context.Context, name string, description *string) (*graph.Group, error) {
	panic(fmt.Errorf("not implemented: CreateGroup - createGroup"))
}

// UpdateGroup is the resolver for the updateGroup field.
func (r *mutationResolver) UpdateGroup(ctx context.Context, id string, name *string, description *string) (*graph.Group, error) {
	panic(fmt.Errorf("not implemented: UpdateGroup - updateGroup"))
}

// DeleteGroup is the resolver for the deleteGroup field.
func (r *mutationResolver) DeleteGroup(ctx context.Context, id string) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteGroup - deleteGroup"))
}

// AddGroupMember is the resolver for the addGroupMember field.
func (r *mutationResolver) AddGroupMember(ctx context.Context, groupID string, userID string) (*graph.Group, error) {
	panic(fmt.Errorf("not implemented: AddGroupMember - addGroupMember"))
}

// RemoveGroupMember is the resolver for the removeGroupMember field.
func (r *mutationResolver) RemoveGroupMember(ctx context.Context, groupID string, userID string) (*graph.Group, error) {
	panic(fmt.Errorf("not implemented: RemoveGroupMember - removeGroupMember"))
}

// AssignResourceToGroup is the resolver for the assignResourceToGroup field.
func (r *mutationResolver) AssignResourceToGroup(ctx context.Context, resourceID string, groupID string) (*graph.Resource, error) {
	panic(fmt.Errorf("not implemented: AssignResourceToGroup - assignResourceToGroup"))
}

// UnassignResourceFromGroup is the resolver for the unassignResourceFromGroup field.
func (r *mutationResolver) UnassignResourceFromGroup(ctx context.Context, resourceID string, groupID string) (*graph.Resource, error) {
	panic(fmt.Errorf("not implemented: UnassignResourceFromGroup - unassignResourceFromGroup"))
}

// Groups is the resolver for the groups field.
func (r *queryResolver) Groups(ctx context.Context) ([]*graph.Group, error) {
	panic(fmt.Errorf("not implemented: Groups - groups"))
}

// Group is the resolver for the group field.
func (r *queryResolver) Group(ctx context.Context, id string) (*graph.Group, error) {
	panic(fmt.Errorf("not implemented: Group - group"))
}
