package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"errors"
	"fmt"

	"github.com/yourorg/ztna/controller/graph"
	"github.com/yourorg/ztna/controller/internal/policy"
	"github.com/yourorg/ztna/controller/internal/tenant"
)

// CreateGroup is the resolver for the createGroup field.
func (r *mutationResolver) CreateGroup(ctx context.Context, name string, description *string) (*graph.Group, error) {
	tc := tenant.MustGet(ctx)

	row, err := r.PolicyStore.CreateGroup(ctx, tc.TenantID, name, description)
	if err != nil {
		return nil, fmt.Errorf("createGroup: %w", err)
	}
	if err := r.PolicyNotifier.NotifyPolicyChange(ctx, tc.TenantID); err != nil {
		return nil, fmt.Errorf("createGroup notify: %w", err)
	}
	return groupRowToGQL(row, nil, nil), nil
}

// UpdateGroup is the resolver for the updateGroup field.
func (r *mutationResolver) UpdateGroup(ctx context.Context, id string, name *string, description *string) (*graph.Group, error) {
	tc := tenant.MustGet(ctx)

	row, err := r.PolicyStore.UpdateGroup(ctx, id, name, description)
	if err != nil {
		if errors.Is(err, policy.ErrNotFound) {
			return nil, fmt.Errorf("updateGroup: group not found")
		}
		return nil, fmt.Errorf("updateGroup: %w", err)
	}
	if err := r.PolicyNotifier.NotifyPolicyChange(ctx, tc.TenantID); err != nil {
		return nil, fmt.Errorf("updateGroup notify: %w", err)
	}
	return groupRowToGQL(row, nil, nil), nil
}

// DeleteGroup is the resolver for the deleteGroup field.
func (r *mutationResolver) DeleteGroup(ctx context.Context, id string) (bool, error) {
	tc := tenant.MustGet(ctx)

	if err := r.PolicyStore.DeleteGroup(ctx, id); err != nil {
		if errors.Is(err, policy.ErrNotFound) {
			return false, fmt.Errorf("deleteGroup: group not found")
		}
		return false, fmt.Errorf("deleteGroup: %w", err)
	}
	if err := r.PolicyNotifier.NotifyPolicyChange(ctx, tc.TenantID); err != nil {
		return false, fmt.Errorf("deleteGroup notify: %w", err)
	}
	return true, nil
}

// AddGroupMember is the resolver for the addGroupMember field.
func (r *mutationResolver) AddGroupMember(ctx context.Context, groupID string, userID string) (*graph.Group, error) {
	tc := tenant.MustGet(ctx)

	if err := r.PolicyStore.AddGroupMember(ctx, groupID, userID); err != nil {
		return nil, fmt.Errorf("addGroupMember: %w", err)
	}
	if err := r.PolicyNotifier.NotifyPolicyChange(ctx, tc.TenantID); err != nil {
		return nil, fmt.Errorf("addGroupMember notify: %w", err)
	}
	return r.loadGroup(ctx, groupID)
}

// RemoveGroupMember is the resolver for the removeGroupMember field.
func (r *mutationResolver) RemoveGroupMember(ctx context.Context, groupID string, userID string) (*graph.Group, error) {
	tc := tenant.MustGet(ctx)

	if err := r.PolicyStore.RemoveGroupMember(ctx, groupID, userID); err != nil {
		if errors.Is(err, policy.ErrNotFound) {
			return nil, fmt.Errorf("removeGroupMember: member not found")
		}
		return nil, fmt.Errorf("removeGroupMember: %w", err)
	}
	if err := r.PolicyNotifier.NotifyPolicyChange(ctx, tc.TenantID); err != nil {
		return nil, fmt.Errorf("removeGroupMember notify: %w", err)
	}
	return r.loadGroup(ctx, groupID)
}

// AssignResourceToGroup is the resolver for the assignResourceToGroup field.
func (r *mutationResolver) AssignResourceToGroup(ctx context.Context, resourceID string, groupID string) (*graph.Resource, error) {
	tc := tenant.MustGet(ctx)

	if _, err := r.PolicyStore.AssignResourceToGroup(ctx, tc.TenantID, resourceID, groupID); err != nil {
		return nil, fmt.Errorf("assignResourceToGroup: %w", err)
	}
	if err := r.PolicyNotifier.NotifyPolicyChange(ctx, tc.TenantID); err != nil {
		return nil, fmt.Errorf("assignResourceToGroup notify: %w", err)
	}
	return r.loadResourceWithGroups(ctx, tc.TenantID, resourceID)
}

// UnassignResourceFromGroup is the resolver for the unassignResourceFromGroup field.
func (r *mutationResolver) UnassignResourceFromGroup(ctx context.Context, resourceID string, groupID string) (*graph.Resource, error) {
	tc := tenant.MustGet(ctx)

	if err := r.PolicyStore.UnassignResourceFromGroup(ctx, resourceID, groupID); err != nil {
		if errors.Is(err, policy.ErrNotFound) {
			return nil, fmt.Errorf("unassignResourceFromGroup: rule not found")
		}
		return nil, fmt.Errorf("unassignResourceFromGroup: %w", err)
	}
	if err := r.PolicyNotifier.NotifyPolicyChange(ctx, tc.TenantID); err != nil {
		return nil, fmt.Errorf("unassignResourceFromGroup notify: %w", err)
	}
	return r.loadResourceWithGroups(ctx, tc.TenantID, resourceID)
}

// Groups is the resolver for the groups field.
func (r *queryResolver) Groups(ctx context.Context) ([]*graph.Group, error) {
	tc := tenant.MustGet(ctx)

	rows, err := r.PolicyStore.ListGroups(ctx, tc.TenantID)
	if err != nil {
		return nil, fmt.Errorf("groups: %w", err)
	}

	out := make([]*graph.Group, 0, len(rows))
	for _, row := range rows {
		g, err := r.loadGroup(ctx, row.ID)
		if err != nil {
			return nil, err
		}
		out = append(out, g)
	}
	return out, nil
}

// Group is the resolver for the group field.
func (r *queryResolver) Group(ctx context.Context, id string) (*graph.Group, error) {
	return r.loadGroup(ctx, id)
}
