package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"errors"
	"fmt"
	"strings"

	"github.com/google/uuid"
	"github.com/yourorg/ztna/controller/graph"
	"github.com/yourorg/ztna/controller/internal/posture"
	"github.com/yourorg/ztna/controller/internal/tenant"
)

// CreateDeviceProfile is the resolver for the createDeviceProfile field.
func (r *mutationResolver) CreateDeviceProfile(ctx context.Context, name string) (*graph.DeviceProfile, error) {
	tc := tenant.MustGet(ctx)

	workspaceID, err := uuid.Parse(tc.TenantID)
	if err != nil {
		return nil, fmt.Errorf("invalid workspace id: %w", err)
	}

	profile, err := r.PostureStore.CreateProfile(ctx, workspaceID, name)
	if err != nil {
		return nil, fmt.Errorf("createDeviceProfile: %w", err)
	}
	if err := r.PolicyNotifier.NotifyPolicyChange(ctx, tc.TenantID); err != nil {
		return nil, fmt.Errorf("createDeviceProfile notify: %w", err)
	}

	return postureProfileToGQL(profile), nil
}

// UpdateDeviceProfileMode is the resolver for the updateDeviceProfileMode field.
func (r *mutationResolver) UpdateDeviceProfileMode(ctx context.Context, id string, mode graph.DeviceProfileMode) (*graph.DeviceProfile, error) {
	tc := tenant.MustGet(ctx)

	workspaceID, err := uuid.Parse(tc.TenantID)
	if err != nil {
		return nil, fmt.Errorf("invalid workspace id: %w", err)
	}

	profileID, err := uuid.Parse(id)
	if err != nil {
		return nil, fmt.Errorf("invalid profile id: %w", err)
	}

	profile, err := r.PostureStore.UpdateProfileMode(
		ctx,
		workspaceID,
		profileID,
		strings.ToLower(string(mode)),
	)
	if err != nil {
		if errors.Is(err, posture.ErrEmptyEnforceProfile) {
			return nil, fmt.Errorf("updateDeviceProfileMode: enforce mode requires at least one requirement")
		}
		if errors.Is(err, posture.ErrNotFound) {
			return nil, fmt.Errorf("updateDeviceProfileMode: profile not found")
		}
		return nil, fmt.Errorf("updateDeviceProfileMode: %w", err)
	}
	if err := r.PolicyNotifier.NotifyPolicyChange(ctx, tc.TenantID); err != nil {
		return nil, fmt.Errorf("updateDeviceProfileMode notify: %w", err)
	}

	return postureProfileToGQL(profile), nil
}

// SupportedPostureChecks is the resolver for the supportedPostureChecks field.
func (r *queryResolver) SupportedPostureChecks(ctx context.Context) ([]*graph.PostureCheckDescriptor, error) {
	checks := posture.SupportedCheckDescriptors()

	result := make([]*graph.PostureCheckDescriptor, len(checks))
	for i, check := range checks {
		result[i] = &graph.PostureCheckDescriptor{
			ID:                         check.ID,
			Label:                      check.Label,
			Platform:                   check.Platform,
			AllowUnsupportedMeaningful: check.AllowUnsupportedMeaningful,
		}
	}

	return result, nil
}

// DeviceProfiles is the resolver for the deviceProfiles field.
func (r *queryResolver) DeviceProfiles(ctx context.Context) ([]*graph.DeviceProfile, error) {
	tc := tenant.MustGet(ctx)

	workspaceID, err := uuid.Parse(tc.TenantID)
	if err != nil {
		return nil, fmt.Errorf("invalid workspace id: %w", err)
	}

	profiles, err := r.PostureStore.ListProfiles(ctx, workspaceID)
	if err != nil {
		return nil, fmt.Errorf("deviceProfiles: %w", err)
	}

	result := make([]*graph.DeviceProfile, len(profiles))
	for i, p := range profiles {
		result[i] = postureProfileToGQL(&p)
	}

	return result, nil
}

func postureProfileToGQL(profile *posture.Profile) *graph.DeviceProfile {
	return &graph.DeviceProfile{
		ID:   profile.ID.String(),
		Name: profile.Name,
		Mode: graph.DeviceProfileMode(strings.ToUpper(profile.Mode)),
	}
}
