package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"fmt"

	"github.com/yourorg/ztna/controller/graph"
)

// CreateResource is the resolver for the createResource field.
func (r *mutationResolver) CreateResource(ctx context.Context, input graph.CreateResourceInput) (*graph.Resource, error) {
	panic(fmt.Errorf("not implemented: CreateResource - createResource"))
}

// ProtectResource is the resolver for the protectResource field.
func (r *mutationResolver) ProtectResource(ctx context.Context, id string) (*graph.Resource, error) {
	panic(fmt.Errorf("not implemented: ProtectResource - protectResource"))
}

// UnprotectResource is the resolver for the unprotectResource field.
func (r *mutationResolver) UnprotectResource(ctx context.Context, id string) (*graph.Resource, error) {
	panic(fmt.Errorf("not implemented: UnprotectResource - unprotectResource"))
}

// DeleteResource is the resolver for the deleteResource field.
func (r *mutationResolver) DeleteResource(ctx context.Context, id string) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteResource - deleteResource"))
}

// Resources is the resolver for the resources field.
func (r *queryResolver) Resources(ctx context.Context, remoteNetworkID string) ([]*graph.Resource, error) {
	panic(fmt.Errorf("not implemented: Resources - resources"))
}

// AllResources is the resolver for the allResources field.
func (r *queryResolver) AllResources(ctx context.Context) ([]*graph.Resource, error) {
	panic(fmt.Errorf("not implemented: AllResources - allResources"))
}
