package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"

	"github.com/yourorg/ztna/controller/graph"
	"github.com/yourorg/ztna/controller/internal/audit"
	"github.com/yourorg/ztna/controller/internal/connector"
	"github.com/yourorg/ztna/controller/internal/resource"
	"github.com/yourorg/ztna/controller/internal/tenant"
)

// CreateResource is the resolver for the createResource field.
func (r *mutationResolver) CreateResource(ctx context.Context, input graph.CreateResourceInput) (*graph.Resource, error) {
	tc := tenant.MustGet(ctx)

	row, err := resource.Create(ctx, r.ResourceCfg.DB, tc.TenantID, resource.CreateInput{
		RemoteNetworkID: input.RemoteNetworkID,
		Name:            input.Name,
		Description:     input.Description,
		Host:            input.Host,
		Protocol:        input.Protocol,
		PortFrom:        input.PortFrom,
		PortTo:          input.PortTo,
	})
	if err != nil {
		return nil, fmt.Errorf("createResource: %w", err)
	}
	if err := r.PolicyNotifier.NotifyPolicyChange(ctx, tc.TenantID); err != nil {
		return nil, fmt.Errorf("createResource: notify policy change: %w", err)
	}

	return toResourceGQL(row), nil
}

// UpdateResource is the resolver for the updateResource field.
func (r *mutationResolver) UpdateResource(ctx context.Context, id string, input graph.UpdateResourceInput) (*graph.Resource, error) {
	tc := tenant.MustGet(ctx)

	updIn := resource.UpdateInput{
		RemoteNetworkID: input.RemoteNetworkID,
		Name:            input.Name,
		Description:     input.Description,
		Protocol:        input.Protocol,
		PortFrom:        input.PortFrom,
		PortTo:          input.PortTo,
	}
	row, err := resource.Update(ctx, r.ResourceCfg.DB, tc.TenantID, id, updIn)
	if err != nil {
		return nil, fmt.Errorf("updateResource: %w", err)
	}
	if err := r.PolicyNotifier.NotifyPolicyChange(ctx, tc.TenantID); err != nil {
		return nil, fmt.Errorf("updateResource: notify policy change: %w", err)
	}

	// Only invalidate the per-workspace ACL snapshot when the update touched a
	// compiler-visible field (name/protocol/port_from). description/port_to/
	// remote_network_id are invisible to the compiler, so changing only those
	// must not churn the ACL version or trigger a fan-out push.
	if resource.ACLRelevantUpdate(updIn) {
		if err := r.PolicyNotifier.NotifyPolicyChange(ctx, tc.TenantID); err != nil {
			return nil, fmt.Errorf("updateResource notify: %w", err)
		}
	}

	return toResourceGQL(row), nil
}

// ProtectResource is the resolver for the protectResource field.
func (r *mutationResolver) ProtectResource(ctx context.Context, id string) (*graph.Resource, error) {
	tc := tenant.MustGet(ctx)

	row, err := resource.MarkProtecting(ctx, r.ResourceCfg.DB, tc.TenantID, id)
	if err != nil {
		return nil, fmt.Errorf("protectResource: %w", err)
	}
	if err := r.PolicyNotifier.NotifyPolicyChange(ctx, tc.TenantID); err != nil {
		return nil, fmt.Errorf("protectResource: notify policy change: %w", err)
	}

	r.ConnectorRegistry.PushInstruction(row)
	connector.PushSnapshotForShield(ctx, r.Pool, r.ConnectorRegistry, row.ConnectorID, row.ShieldID)
	return toResourceGQL(row), nil
}

// UnprotectResource is the resolver for the unprotectResource field.
func (r *mutationResolver) UnprotectResource(ctx context.Context, id string) (*graph.Resource, error) {
	tc := tenant.MustGet(ctx)

	row, err := resource.MarkUnprotecting(ctx, r.ResourceCfg.DB, tc.TenantID, id)
	if err != nil {
		return nil, fmt.Errorf("unprotectResource: %w", err)
	}

	// Only instruct a shield when there is one to instruct. If the bound shield was
	// revoked/gone, MarkUnprotecting resolved straight to 'unprotected' (Finding 7):
	// no shield to remove the rule or ack, so there is nothing to push.
	if row.Status == "protecting" {
		r.ConnectorRegistry.PushInstruction(row)
		connector.PushSnapshotForShield(ctx, r.Pool, r.ConnectorRegistry, row.ConnectorID, row.ShieldID)
	} else if err := r.PolicyNotifier.NotifyPolicyChange(ctx, tc.TenantID); err != nil {
		return nil, fmt.Errorf("unprotectResource: notify policy change: %w", err)
	}
	return toResourceGQL(row), nil
}

// DeleteResource is the resolver for the deleteResource field.
func (r *mutationResolver) DeleteResource(ctx context.Context, id string) (bool, error) {
	tc := tenant.MustGet(ctx)

	row, err := resource.GetByID(ctx, r.ResourceCfg.DB, tc.TenantID, id)
	if err != nil {
		return false, fmt.Errorf("deleteResource: %w", err)
	}

	switch row.Status {
	case "protecting", "deleting":
		return false, fmt.Errorf("deleteResource: resource is mid-operation; wait for it to finish")
	case "protected", "failed":
		// May hold a shield rule → tombstone + tell the shield to remove it.
		// The row is reaped by RecordAck once the shield acks removal.
		delRow, err := resource.MarkDeleting(ctx, r.ResourceCfg.DB, tc.TenantID, id)
		if err != nil {
			return false, fmt.Errorf("deleteResource: %w", err)
		}
		r.ConnectorRegistry.PushInstruction(delRow)
		connector.PushSnapshotForShield(ctx, r.Pool, r.ConnectorRegistry, row.ConnectorID, row.ShieldID)
		if err := r.PolicyNotifier.NotifyPolicyChange(ctx, tc.TenantID); err != nil {
			return false, fmt.Errorf("deleteResource: notify policy change: %w", err)
		}
		return true, nil
	default: // pending, unprotected — no rule possible, delete now
		if err := resource.DeleteRow(ctx, r.ResourceCfg.DB, tc.TenantID, id); err != nil {
			return false, fmt.Errorf("deleteResource: %w", err)
		}
		// The row left the ACL compiler's output — invalidate the workspace snapshot.
		if err := r.PolicyNotifier.NotifyPolicyChange(ctx, tc.TenantID); err != nil {
			return false, fmt.Errorf("deleteResource notify: %w", err)
		}
		return true, nil
	}
}

// ForceDeleteResource is the resolver for the forceDeleteResource field — the
// break-glass escape hatch (ADR-004 Phase 4). It hard-deletes a resource in ANY
// state, including a 'deleting' tombstone or a 'protecting' row stuck because its
// shield is permanently gone and will never ack. This deliberately bypasses the
// confirmation-gated tombstone path, so it is admin-only (@hasRole) and every call
// is audit-logged. Best-effort: if the shield turns out to still be connected, the
// re-pushed snapshot makes it drop the now-removed rule (replace semantics).
func (r *mutationResolver) ForceDeleteResource(ctx context.Context, id string) (bool, error) {
	tc := tenant.MustGet(ctx)

	// Snapshot the row for the audit record before it's gone. Best-effort — even if
	// it can't be loaded we still attempt the delete; the whole point is rescuing a
	// resource the normal path can't.
	row, _ := resource.GetByID(ctx, r.ResourceCfg.DB, tc.TenantID, id)

	deleted, err := resource.ForceDeleteRow(ctx, r.ResourceCfg.DB, tc.TenantID, id)
	if err != nil {
		return false, fmt.Errorf("forceDeleteResource: %w", err)
	}
	if !deleted {
		return false, fmt.Errorf("forceDeleteResource: resource not found")
	}

	// Durable audit trail — this bypassed the safety model, so it MUST leave a
	// record. The delete already happened; a failed audit write is logged, not fatal.
	details := map[string]any{}
	if row != nil {
		details["name"] = row.Name
		details["host"] = row.Host
		details["status"] = row.Status
		details["shield_id"] = row.ShieldID
		details["connector_id"] = row.ConnectorID
	}
	_ = audit.Record(ctx, r.Pool, audit.Entry{
		TenantID:    tc.TenantID,
		ActorUserID: tc.UserID,
		ActorEmail:  tc.Email,
		Action:      "resource.force_delete",
		TargetType:  "resource",
		TargetID:    id,
		Details:     details,
	})

	// Best-effort: if the shield is in fact still connected, re-push its desired set
	// so it drops the rule for the resource we just removed.
	if row != nil && row.ConnectorID != "" && row.ShieldID != "" {
		connector.PushSnapshotForShield(ctx, r.Pool, r.ConnectorRegistry, row.ConnectorID, row.ShieldID)
	}
	if err := r.PolicyNotifier.NotifyPolicyChange(ctx, tc.TenantID); err != nil {
		return false, fmt.Errorf("forceDeleteResource: notify policy change: %w", err)
	}

	// The row left the ACL compiler's output — invalidate the workspace snapshot.
	if err := r.PolicyNotifier.NotifyPolicyChange(ctx, tc.TenantID); err != nil {
		return false, fmt.Errorf("forceDeleteResource notify: %w", err)
	}

	return true, nil
}

// Resources is the resolver for the resources field.
func (r *queryResolver) Resources(ctx context.Context, remoteNetworkID string) ([]*graph.Resource, error) {
	tc := tenant.MustGet(ctx)

	rows, err := resource.GetByRemoteNetwork(ctx, r.ResourceCfg.DB, tc.TenantID, remoteNetworkID)
	if err != nil {
		return nil, fmt.Errorf("resources: %w", err)
	}

	result := make([]*graph.Resource, len(rows))
	for i, row := range rows {
		result[i] = toResourceGQL(row)
	}
	return result, nil
}

// AllResources is the resolver for the allResources field.
func (r *queryResolver) AllResources(ctx context.Context) ([]*graph.Resource, error) {
	tc := tenant.MustGet(ctx)

	rows, err := resource.GetAll(ctx, r.ResourceCfg.DB, tc.TenantID)
	if err != nil {
		return nil, fmt.Errorf("allResources: %w", err)
	}

	result := make([]*graph.Resource, len(rows))
	for i, row := range rows {
		result[i] = toResourceGQL(row)
	}
	return result, nil
}
