package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"errors"
	"fmt"

	"github.com/google/uuid"
	"github.com/yourorg/ztna/controller/graph"
	"github.com/yourorg/ztna/controller/internal/apperr"
	"github.com/yourorg/ztna/controller/internal/posture"
	"github.com/yourorg/ztna/controller/internal/resource"
	"github.com/yourorg/ztna/controller/internal/tenant"
)

// CreateResourcePolicy is the resolver for the createResourcePolicy field.
func (r *mutationResolver) CreateResourcePolicy(ctx context.Context, name string) (*graph.ResourcePolicy, error) {
	tc := tenant.MustGet(ctx)

	workspaceID, err := uuid.Parse(tc.TenantID)
	if err != nil {
		return nil, fmt.Errorf("invalid workspace id: %w", err)
	}

	policy, err := r.PostureStore.CreateResourcePolicy(ctx, workspaceID, name)
	if err != nil {
		switch {
		case errors.Is(err, posture.ErrInvalidPolicyName):
			return nil, apperr.UserErrorf("createResourcePolicy: name is required")

		case errors.Is(err, posture.ErrDuplicatePolicyName):
			return nil, apperr.UserErrorf("createResourcePolicy: a resource policy with that name already exists")

		default:
			return nil, fmt.Errorf("createResourcePolicy: %w", err)
		}
	}

	if err := r.PolicyNotifier.NotifyPolicyChange(ctx, tc.TenantID); err != nil {
		return nil, fmt.Errorf("createResourcePolicy notify: %w", err)
	}

	return resourcePolicyToGQL(policy), nil
}

// UpdateResourcePolicy is the resolver for the updateResourcePolicy field.
func (r *mutationResolver) UpdateResourcePolicy(ctx context.Context, id string, name string) (*graph.ResourcePolicy, error) {
	tc := tenant.MustGet(ctx)

	workspaceID, err := uuid.Parse(tc.TenantID)
	if err != nil {
		return nil, fmt.Errorf("invalid workspace id: %w", err)
	}

	policyID, err := uuid.Parse(id)
	if err != nil {
		return nil, apperr.UserErrorf("invalid resource policy id")
	}

	policy, err := r.PostureStore.UpdateResourcePolicy(ctx, workspaceID, policyID, name)
	if err != nil {
		switch {
		case errors.Is(err, posture.ErrInvalidPolicyName):
			return nil, apperr.UserErrorf("updateResourcePolicy: name is required")

		case errors.Is(err, posture.ErrDuplicatePolicyName):
			return nil, apperr.UserErrorf("updateResourcePolicy: a resource policy with that name already exists")

		case errors.Is(err, posture.ErrNotFound):
			return nil, apperr.UserErrorf("updateResourcePolicy: resource policy not found")

		default:
			return nil, fmt.Errorf("updateResourcePolicy: %w", err)
		}
	}

	if err := r.PolicyNotifier.NotifyPolicyChange(ctx, tc.TenantID); err != nil {
		return nil, fmt.Errorf("updateResourcePolicy notify: %w", err)
	}

	return resourcePolicyToGQL(policy), nil
}

// DeleteResourcePolicy is the resolver for the deleteResourcePolicy field.
func (r *mutationResolver) DeleteResourcePolicy(ctx context.Context, id string) (bool, error) {
	tc := tenant.MustGet(ctx)

	workspaceID, err := uuid.Parse(tc.TenantID)
	if err != nil {
		return false, fmt.Errorf("invalid workspace id: %w", err)
	}

	policyID, err := uuid.Parse(id)
	if err != nil {
		return false, apperr.UserErrorf("invalid resource policy id")
	}

	if err := r.PostureStore.DeleteResourcePolicy(ctx, workspaceID, policyID); err != nil {
		switch {
		case errors.Is(err, posture.ErrPolicyAssigned):
			return false, apperr.UserErrorf(
				"deleteResourcePolicy: resource policy is still assigned to a resource",
			)

		case errors.Is(err, posture.ErrWorkspaceMismatch):
			return false, apperr.UserErrorf("deleteResourcePolicy: resource policy not found")

		case errors.Is(err, posture.ErrNotFound):
			return false, apperr.UserErrorf("deleteResourcePolicy: resource policy not found")

		default:
			return false, fmt.Errorf("deleteResourcePolicy: %w", err)
		}
	}

	if err := r.PolicyNotifier.NotifyPolicyChange(ctx, tc.TenantID); err != nil {
		return false, fmt.Errorf("deleteResourcePolicy notify: %w", err)
	}

	return true, nil
}

// AssignResourcePolicy is the resolver for the assignResourcePolicy field.
func (r *mutationResolver) AssignResourcePolicy(ctx context.Context, resourceID string, policyID string) (*graph.Resource, error) {
	tc := tenant.MustGet(ctx)

	workspaceID, err := uuid.Parse(tc.TenantID)
	if err != nil {
		return nil, fmt.Errorf("invalid workspace id: %w", err)
	}

	resourceUUID, err := uuid.Parse(resourceID)
	if err != nil {
		return nil, apperr.UserErrorf("invalid resource id")
	}

	policyUUID, err := uuid.Parse(policyID)
	if err != nil {
		return nil, apperr.UserErrorf("invalid resource policy id")
	}

	if err := r.PostureStore.AssignResourcePolicy(
		ctx,
		workspaceID,
		resourceUUID,
		policyUUID,
	); err != nil {
		switch {
		case errors.Is(err, posture.ErrResourceAlreadyAssigned):
			return nil, apperr.UserErrorf(
				"assignResourcePolicy: resource already has a different resource policy",
			)

		case errors.Is(err, posture.ErrWorkspaceMismatch):
			return nil, apperr.UserErrorf("assignResourcePolicy: resource or resource policy not found")

		case errors.Is(err, posture.ErrNotFound):
			return nil, apperr.UserErrorf("assignResourcePolicy: resource or resource policy not found")

		default:
			return nil, fmt.Errorf("assignResourcePolicy: %w", err)
		}
	}

	if err := r.PolicyNotifier.NotifyPolicyChange(ctx, tc.TenantID); err != nil {
		return nil, fmt.Errorf("assignResourcePolicy notify: %w", err)
	}

	row, err := resource.GetByID(ctx, r.ResourceCfg.DB, tc.TenantID, resourceID)
	if err != nil {
		return nil, fmt.Errorf("assignResourcePolicy: load resource: %w", err)
	}

	return toResourceGQL(row), nil
}

// UnassignResourcePolicy is the resolver for the unassignResourcePolicy field.
func (r *mutationResolver) UnassignResourcePolicy(ctx context.Context, resourceID string) (*graph.Resource, error) {
	tc := tenant.MustGet(ctx)

	workspaceID, err := uuid.Parse(tc.TenantID)
	if err != nil {
		return nil, fmt.Errorf("invalid workspace id: %w", err)
	}

	resourceUUID, err := uuid.Parse(resourceID)
	if err != nil {
		return nil, apperr.UserErrorf("invalid resource id")
	}

	if err := r.PostureStore.UnassignResourcePolicy(
		ctx,
		workspaceID,
		resourceUUID,
	); err != nil {
		switch {
		case errors.Is(err, posture.ErrNotFound):
			return nil, apperr.UserErrorf("unassignResourcePolicy: resource not found")

		default:
			return nil, fmt.Errorf("unassignResourcePolicy: %w", err)
		}
	}

	if err := r.PolicyNotifier.NotifyPolicyChange(ctx, tc.TenantID); err != nil {
		return nil, fmt.Errorf("unassignResourcePolicy notify: %w", err)
	}

	row, err := resource.GetByID(ctx, r.ResourceCfg.DB, tc.TenantID, resourceID)
	if err != nil {
		return nil, fmt.Errorf("unassignResourcePolicy: load resource: %w", err)
	}

	return toResourceGQL(row), nil
}

// AddProfileToResourcePolicy is the resolver for the addProfileToResourcePolicy field.
func (r *mutationResolver) AddProfileToResourcePolicy(ctx context.Context, policyID string, profileID string) (*graph.ResourcePolicy, error) {
	tc := tenant.MustGet(ctx)

	workspaceID, err := uuid.Parse(tc.TenantID)
	if err != nil {
		return nil, fmt.Errorf("invalid workspace id: %w", err)
	}

	policyUUID, err := uuid.Parse(policyID)
	if err != nil {
		return nil, apperr.UserErrorf("invalid resource policy id")
	}

	profileUUID, err := uuid.Parse(profileID)
	if err != nil {
		return nil, apperr.UserErrorf("invalid profile id")
	}

	if err := r.PostureStore.AddProfileToPolicy(
		ctx,
		workspaceID,
		policyUUID,
		profileUUID,
	); err != nil {
		switch {
		case errors.Is(err, posture.ErrDuplicateProfileBinding):
			return nil, apperr.UserErrorf(
				"addProfileToResourcePolicy: device profile is already attached to this resource policy",
			)

		case errors.Is(err, posture.ErrWorkspaceMismatch):
			return nil, apperr.UserErrorf(
				"addProfileToResourcePolicy: resource policy or device profile not found",
			)

		case errors.Is(err, posture.ErrNotFound):
			return nil, apperr.UserErrorf(
				"addProfileToResourcePolicy: resource policy or device profile not found",
			)

		default:
			return nil, fmt.Errorf("addProfileToResourcePolicy: %w", err)
		}
	}

	if err := r.PolicyNotifier.NotifyPolicyChange(ctx, tc.TenantID); err != nil {
		return nil, fmt.Errorf("addProfileToResourcePolicy notify: %w", err)
	}

	policy, err := r.PostureStore.GetResourcePolicy(ctx, workspaceID, policyUUID)
	if err != nil {
		return nil, fmt.Errorf("addProfileToResourcePolicy: %w", err)
	}

	return resourcePolicyToGQL(policy), nil
}

// RemoveProfileFromResourcePolicy is the resolver for the removeProfileFromResourcePolicy field.
func (r *mutationResolver) RemoveProfileFromResourcePolicy(ctx context.Context, policyID string, profileID string) (*graph.ResourcePolicy, error) {
	tc := tenant.MustGet(ctx)

	workspaceID, err := uuid.Parse(tc.TenantID)
	if err != nil {
		return nil, fmt.Errorf("invalid workspace id: %w", err)
	}

	policyUUID, err := uuid.Parse(policyID)
	if err != nil {
		return nil, apperr.UserErrorf("invalid resource policy id")
	}

	profileUUID, err := uuid.Parse(profileID)
	if err != nil {
		return nil, apperr.UserErrorf("invalid profile id")
	}

	if err := r.PostureStore.RemoveProfileFromPolicy(
		ctx,
		workspaceID,
		policyUUID,
		profileUUID,
	); err != nil {
		switch {
		case errors.Is(err, posture.ErrNotFound):
			return nil, apperr.UserErrorf(
				"removeProfileFromResourcePolicy: profile attachment not found",
			)

		default:
			return nil, fmt.Errorf("removeProfileFromResourcePolicy: %w", err)
		}
	}

	if err := r.PolicyNotifier.NotifyPolicyChange(ctx, tc.TenantID); err != nil {
		return nil, fmt.Errorf("removeProfileFromResourcePolicy notify: %w", err)
	}

	policy, err := r.PostureStore.GetResourcePolicy(ctx, workspaceID, policyUUID)
	if err != nil {
		return nil, fmt.Errorf("removeProfileFromResourcePolicy: %w", err)
	}

	return resourcePolicyToGQL(policy), nil
}

// ResourcePolicies is the resolver for the resourcePolicies field.
func (r *queryResolver) ResourcePolicies(ctx context.Context) ([]*graph.ResourcePolicy, error) {
	tc := tenant.MustGet(ctx)

	workspaceID, err := uuid.Parse(tc.TenantID)
	if err != nil {
		return nil, fmt.Errorf("invalid workspace id: %w", err)
	}

	policies, err := r.PostureStore.ListResourcePolicies(ctx, workspaceID)
	if err != nil {
		return nil, fmt.Errorf("resourcePolicies: %w", err)
	}

	result := make([]*graph.ResourcePolicy, len(policies))
	for i := range policies {
		result[i] = resourcePolicyToGQL(&policies[i])
	}

	return result, nil
}

// ResourcePolicy is the resolver for the resourcePolicy field.
func (r *queryResolver) ResourcePolicy(ctx context.Context, id string) (*graph.ResourcePolicy, error) {
	tc := tenant.MustGet(ctx)

	workspaceID, err := uuid.Parse(tc.TenantID)
	if err != nil {
		return nil, fmt.Errorf("invalid workspace id: %w", err)
	}

	policyID, err := uuid.Parse(id)
	if err != nil {
		return nil, apperr.UserErrorf("invalid resource policy id")
	}

	policy, err := r.PostureStore.GetResourcePolicy(ctx, workspaceID, policyID)
	if err != nil {
		if errors.Is(err, posture.ErrNotFound) {
			return nil, apperr.UserErrorf("resourcePolicy: resource policy not found")
		}
		return nil, fmt.Errorf("resourcePolicy: %w", err)
	}

	return resourcePolicyToGQL(policy), nil
}

// ResourcePolicy is the resolver for the resourcePolicy field.
func (r *resourceResolver) ResourcePolicy(ctx context.Context, obj *graph.Resource) (*graph.ResourcePolicy, error) {
	tc := tenant.MustGet(ctx)

	workspaceID, err := uuid.Parse(tc.TenantID)
	if err != nil {
		return nil, fmt.Errorf("invalid workspace id: %w", err)
	}

	resourceID, err := uuid.Parse(obj.ID)
	if err != nil {
		return nil, fmt.Errorf("invalid resource id: %w", err)
	}

	// Targeted per-resource lookup; nil means the resource carries no policy,
	// which the schema exposes as null rather than an error.
	policy, err := r.PostureStore.GetResourcePolicyForResource(
		ctx,
		workspaceID,
		resourceID,
	)
	if err != nil {
		return nil, fmt.Errorf("resourcePolicy: %w", err)
	}
	if policy == nil {
		return nil, nil
	}

	return resourcePolicyToGQL(policy), nil
}

// DeviceProfiles is the resolver for the deviceProfiles field.
func (r *resourcePolicyResolver) DeviceProfiles(ctx context.Context, obj *graph.ResourcePolicy) ([]*graph.DeviceProfile, error) {
	tc := tenant.MustGet(ctx)

	workspaceID, err := uuid.Parse(tc.TenantID)
	if err != nil {
		return nil, fmt.Errorf("invalid workspace id: %w", err)
	}

	policyID, err := uuid.Parse(obj.ID)
	if err != nil {
		return nil, fmt.Errorf("invalid resource policy id: %w", err)
	}

	profiles, err := r.PostureStore.ListProfilesForPolicy(ctx, workspaceID, policyID)
	if err != nil {
		return nil, fmt.Errorf("deviceProfiles: %w", err)
	}

	// An empty list is a valid state meaning "Any Device".
	result := make([]*graph.DeviceProfile, len(profiles))
	for i := range profiles {
		result[i] = postureProfileToGQL(&profiles[i])
	}

	return result, nil
}

// Resources is the resolver for the resources field.
func (r *resourcePolicyResolver) Resources(ctx context.Context, obj *graph.ResourcePolicy) ([]*graph.Resource, error) {
	tc := tenant.MustGet(ctx)

	workspaceID, err := uuid.Parse(tc.TenantID)
	if err != nil {
		return nil, fmt.Errorf("invalid workspace id: %w", err)
	}

	policyID, err := uuid.Parse(obj.ID)
	if err != nil {
		return nil, fmt.Errorf("invalid resource policy id: %w", err)
	}

	resourceIDs, err := r.PostureStore.ListResourceIDsForPolicy(ctx, workspaceID, policyID)
	if err != nil {
		return nil, fmt.Errorf("resources: %w", err)
	}

	rows, err := resource.GetByIDs(ctx, r.ResourceCfg.DB, tc.TenantID, resourceIDs)
	if err != nil {
		return nil, fmt.Errorf("resources: load resources: %w", err)
	}

	result := make([]*graph.Resource, len(rows))
	for i, row := range rows {
		result[i] = toResourceGQL(row)
	}

	return result, nil
}

// ResourcePolicy returns graph.ResourcePolicyResolver implementation.
func (r *Resolver) ResourcePolicy() graph.ResourcePolicyResolver { return &resourcePolicyResolver{r} }

type resourcePolicyResolver struct{ *Resolver }
