package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"fmt"

	"github.com/yourorg/ztna/controller/graph"
	"github.com/yourorg/ztna/controller/internal/resource"
	"github.com/yourorg/ztna/controller/internal/tenant"
)

// CreateResource is the resolver for the createResource field.
func (r *mutationResolver) CreateResource(ctx context.Context, input graph.CreateResourceInput) (*graph.Resource, error) {
	tc := tenant.MustGet(ctx)

	row, err := resource.Create(ctx, r.ResourceCfg.DB, tc.TenantID, resource.CreateInput{
		Name:        input.Name,
		Description: input.Description,
		Host:        input.Host,
		Protocol:    input.Protocol,
		PortFrom:    input.PortFrom,
		PortTo:      input.PortTo,
	})
	if err != nil {
		return nil, fmt.Errorf("createResource: %w", err)
	}

	return toResourceGQL(row), nil
}

// ProtectResource is the resolver for the protectResource field.
func (r *mutationResolver) ProtectResource(ctx context.Context, id string) (*graph.Resource, error) {
	tc := tenant.MustGet(ctx)

	row, err := resource.MarkManaging(ctx, r.ResourceCfg.DB, tc.TenantID, id)
	if err != nil {
		return nil, fmt.Errorf("protectResource: %w", err)
	}

	return toResourceGQL(row), nil
}

// UnprotectResource is the resolver for the unprotectResource field.
func (r *mutationResolver) UnprotectResource(ctx context.Context, id string) (*graph.Resource, error) {
	tc := tenant.MustGet(ctx)

	row, err := resource.MarkRemoving(ctx, r.ResourceCfg.DB, tc.TenantID, id)
	if err != nil {
		return nil, fmt.Errorf("unprotectResource: %w", err)
	}

	return toResourceGQL(row), nil
}

// DeleteResource is the resolver for the deleteResource field.
func (r *mutationResolver) DeleteResource(ctx context.Context, id string) (bool, error) {
	tc := tenant.MustGet(ctx)

	if err := resource.SoftDelete(ctx, r.ResourceCfg.DB, tc.TenantID, id); err != nil {
		return false, fmt.Errorf("deleteResource: %w", err)
	}

	return true, nil
}

// Resources is the resolver for the resources field.
func (r *queryResolver) Resources(ctx context.Context, remoteNetworkID string) ([]*graph.Resource, error) {
	tc := tenant.MustGet(ctx)

	rows, err := resource.GetByRemoteNetwork(ctx, r.ResourceCfg.DB, tc.TenantID, remoteNetworkID)
	if err != nil {
		return nil, fmt.Errorf("resources: %w", err)
	}

	result := make([]*graph.Resource, len(rows))
	for i, row := range rows {
		result[i] = toResourceGQL(row)
	}
	return result, nil
}

// AllResources is the resolver for the allResources field.
func (r *queryResolver) AllResources(ctx context.Context) ([]*graph.Resource, error) {
	tc := tenant.MustGet(ctx)

	rows, err := resource.GetAll(ctx, r.ResourceCfg.DB, tc.TenantID)
	if err != nil {
		return nil, fmt.Errorf("allResources: %w", err)
	}

	result := make([]*graph.Resource, len(rows))
	for i, row := range rows {
		result[i] = toResourceGQL(row)
	}
	return result, nil
}
