package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"fmt"
	"strings"

	"github.com/yourorg/ztna/controller/graph"
	"github.com/yourorg/ztna/controller/graph/model"
	"github.com/yourorg/ztna/controller/internal/models"
	"github.com/yourorg/ztna/controller/internal/tenant"
)

// InitiateAuth is the resolver for the initiateAuth field.
func (r *mutationResolver) InitiateAuth(ctx context.Context, provider string, workspaceName *string) (*model.AuthInitPayload, error) {
	return r.AuthService.InitiateAuth(ctx, provider, workspaceName)
}

// CreateRemoteNetwork is the resolver for the createRemoteNetwork field.
func (r *mutationResolver) CreateRemoteNetwork(ctx context.Context, name string, location graph.NetworkLocation) (*graph.RemoteNetwork, error) {
	panic(fmt.Errorf("not implemented: CreateRemoteNetwork - createRemoteNetwork"))
}

// DeleteRemoteNetwork is the resolver for the deleteRemoteNetwork field.
func (r *mutationResolver) DeleteRemoteNetwork(ctx context.Context, id string) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteRemoteNetwork - deleteRemoteNetwork"))
}

// GenerateConnectorToken is the resolver for the generateConnectorToken field.
func (r *mutationResolver) GenerateConnectorToken(ctx context.Context, remoteNetworkID string, connectorName string) (*graph.ConnectorToken, error) {
	panic(fmt.Errorf("not implemented: GenerateConnectorToken - generateConnectorToken"))
}

// RevokeConnector is the resolver for the revokeConnector field.
func (r *mutationResolver) RevokeConnector(ctx context.Context, id string) (bool, error) {
	panic(fmt.Errorf("not implemented: RevokeConnector - revokeConnector"))
}

// DeleteConnector is the resolver for the deleteConnector field.
func (r *mutationResolver) DeleteConnector(ctx context.Context, id string) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteConnector - deleteConnector"))
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*models.User, error) {
	tc := tenant.MustGet(ctx)

	var u models.User
	err := r.TenantDB.QueryRow(ctx,
		`SELECT id, tenant_id, email, provider, provider_sub,
		        role, status, last_login_at, created_at, updated_at
		 FROM users
		 WHERE id        = $1
		   AND tenant_id = $2
		   AND status    = 'active'`,
		tc.UserID, tc.TenantID,
	).Scan(
		&u.ID, &u.TenantID, &u.Email,
		&u.Provider, &u.ProviderSub,
		&u.Role, &u.Status, &u.LastLoginAt,
		&u.CreatedAt, &u.UpdatedAt,
	)
	if err != nil {
		return nil, fmt.Errorf("me: %w", err)
	}

	return &u, nil
}

// Workspace is the resolver for the workspace field.
func (r *queryResolver) Workspace(ctx context.Context) (*models.Workspace, error) {
	tc := tenant.MustGet(ctx)

	var ws models.Workspace
	err := r.TenantDB.QueryRow(ctx,
		`SELECT id, slug, name, status, ca_cert_pem, created_at, updated_at
		 FROM workspaces
		 WHERE id = $1`,
		tc.TenantID,
	).Scan(
		&ws.ID, &ws.Slug, &ws.Name,
		&ws.Status, &ws.CACertPEM,
		&ws.CreatedAt, &ws.UpdatedAt,
	)
	if err != nil {
		return nil, fmt.Errorf("workspace: %w", err)
	}

	return &ws, nil
}

// RemoteNetworks is the resolver for the remoteNetworks field.
func (r *queryResolver) RemoteNetworks(ctx context.Context) ([]*graph.RemoteNetwork, error) {
	panic(fmt.Errorf("not implemented: RemoteNetworks - remoteNetworks"))
}

// RemoteNetwork is the resolver for the remoteNetwork field.
func (r *queryResolver) RemoteNetwork(ctx context.Context, id string) (*graph.RemoteNetwork, error) {
	panic(fmt.Errorf("not implemented: RemoteNetwork - remoteNetwork"))
}

// Connectors is the resolver for the connectors field.
func (r *queryResolver) Connectors(ctx context.Context, remoteNetworkID string) ([]*graph.Connector, error) {
	panic(fmt.Errorf("not implemented: Connectors - connectors"))
}

// Role is the resolver for the role field.
func (r *userResolver) Role(ctx context.Context, obj *models.User) (graph.Role, error) {
	role := graph.Role(strings.ToUpper(obj.Role))
	if !role.IsValid() {
		return "", fmt.Errorf("invalid role: %q", obj.Role)
	}

	return role, nil
}

// CreatedAt is the resolver for the createdAt field.
func (r *userResolver) CreatedAt(ctx context.Context, obj *models.User) (string, error) {
	return obj.CreatedAt.Format("2006-01-02T15:04:05Z07:00"), nil
}

// Status is the resolver for the status field.
func (r *workspaceResolver) Status(ctx context.Context, obj *models.Workspace) (graph.WorkspaceStatus, error) {
	status := graph.WorkspaceStatus(strings.ToUpper(obj.Status))
	if !status.IsValid() {
		return "", fmt.Errorf("invalid workspace status: %q", obj.Status)
	}

	return status, nil
}

// CreatedAt is the resolver for the createdAt field.
func (r *workspaceResolver) CreatedAt(ctx context.Context, obj *models.Workspace) (string, error) {
	return obj.CreatedAt.Format("2006-01-02T15:04:05Z07:00"), nil
}

// Mutation returns graph.MutationResolver implementation.
func (r *Resolver) Mutation() graph.MutationResolver { return &mutationResolver{r} }

// Query returns graph.QueryResolver implementation.
func (r *Resolver) Query() graph.QueryResolver { return &queryResolver{r} }

// User returns graph.UserResolver implementation.
func (r *Resolver) User() graph.UserResolver { return &userResolver{r} }

// Workspace returns graph.WorkspaceResolver implementation.
func (r *Resolver) Workspace() graph.WorkspaceResolver { return &workspaceResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type userResolver struct{ *Resolver }
type workspaceResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	func (r *Resolver) RemoteNetwork() graph.RemoteNetworkResolver { return &remoteNetworkResolver{r} }
func (r *Resolver) Connector() graph.ConnectorResolver { return &connectorResolver{r} }
type connectorResolver struct{ *Resolver }
type remoteNetworkResolver struct{ *Resolver }
*/
