package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"fmt"

	"github.com/yourorg/ztna/controller/graph"
	"github.com/yourorg/ztna/controller/graph/model"
	"github.com/yourorg/ztna/controller/internal/models"
)

// InitiateAuth is the resolver for the initiateAuth field.
func (r *mutationResolver) InitiateAuth(ctx context.Context, provider string) (*model.AuthInitPayload, error) {
	panic(fmt.Errorf("not implemented: InitiateAuth - initiateAuth"))
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*models.User, error) {
	panic(fmt.Errorf("not implemented: Me - me"))
}

// Workspace is the resolver for the workspace field.
func (r *queryResolver) Workspace(ctx context.Context) (*models.Workspace, error) {
	panic(fmt.Errorf("not implemented: Workspace - workspace"))
}

// Role is the resolver for the role field.
func (r *userResolver) Role(ctx context.Context, obj *models.User) (graph.Role, error) {
	panic(fmt.Errorf("not implemented: Role - role"))
}

// CreatedAt is the resolver for the createdAt field.
func (r *userResolver) CreatedAt(ctx context.Context, obj *models.User) (string, error) {
	panic(fmt.Errorf("not implemented: CreatedAt - createdAt"))
}

// Status is the resolver for the status field.
func (r *workspaceResolver) Status(ctx context.Context, obj *models.Workspace) (graph.WorkspaceStatus, error) {
	panic(fmt.Errorf("not implemented: Status - status"))
}

// CreatedAt is the resolver for the createdAt field.
func (r *workspaceResolver) CreatedAt(ctx context.Context, obj *models.Workspace) (string, error) {
	panic(fmt.Errorf("not implemented: CreatedAt - createdAt"))
}

// Mutation returns graph.MutationResolver implementation.
func (r *Resolver) Mutation() graph.MutationResolver { return &mutationResolver{r} }

// Query returns graph.QueryResolver implementation.
func (r *Resolver) Query() graph.QueryResolver { return &queryResolver{r} }

// User returns graph.UserResolver implementation.
func (r *Resolver) User() graph.UserResolver { return &userResolver{r} }

// Workspace returns graph.WorkspaceResolver implementation.
func (r *Resolver) Workspace() graph.WorkspaceResolver { return &workspaceResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type userResolver struct{ *Resolver }
type workspaceResolver struct{ *Resolver }
