package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"errors"
	"fmt"
	"strings"

	pgx "github.com/jackc/pgx/v5"
	"github.com/yourorg/ztna/controller/graph"
	"github.com/yourorg/ztna/controller/graph/model"
	"github.com/yourorg/ztna/controller/internal/models"
	"github.com/yourorg/ztna/controller/internal/tenant"
)

// InitiateAuth is the resolver for the initiateAuth field.
func (r *mutationResolver) InitiateAuth(ctx context.Context, provider string, workspaceName *string) (*model.AuthInitPayload, error) {
	return r.AuthService.InitiateAuth(ctx, provider, workspaceName)
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*models.User, error) {
	tc := tenant.MustGet(ctx)

	var u models.User
	err := r.TenantDB.QueryRow(ctx,
		`SELECT id, tenant_id, email, provider, provider_sub,
		        role, status, last_login_at, created_at, updated_at
		 FROM users
		 WHERE id        = $1
		   AND tenant_id = $2
		   AND status    = 'active'`,
		tc.UserID, tc.TenantID,
	).Scan(
		&u.ID, &u.TenantID, &u.Email,
		&u.Provider, &u.ProviderSub,
		&u.Role, &u.Status, &u.LastLoginAt,
		&u.CreatedAt, &u.UpdatedAt,
	)
	if err != nil {
		return nil, fmt.Errorf("me: %w", err)
	}

	return &u, nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*models.User, error) {
	tc := tenant.MustGet(ctx)

	rows, err := r.TenantDB.Query(ctx,
		`SELECT id, tenant_id, email, provider, provider_sub,
		        role, status, last_login_at, created_at, updated_at
		 FROM users
		 WHERE tenant_id = $1
		   AND status    = 'active'
		 ORDER BY email`,
		tc.TenantID,
	)
	if err != nil {
		return nil, fmt.Errorf("users: %w", err)
	}
	defer rows.Close()

	var result []*models.User
	for rows.Next() {
		var u models.User
		if err := rows.Scan(
			&u.ID, &u.TenantID, &u.Email,
			&u.Provider, &u.ProviderSub,
			&u.Role, &u.Status, &u.LastLoginAt,
			&u.CreatedAt, &u.UpdatedAt,
		); err != nil {
			return nil, fmt.Errorf("users scan: %w", err)
		}
		result = append(result, &u)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("users iterate: %w", err)
	}
	return result, nil
}

// Workspace is the resolver for the workspace field.
func (r *queryResolver) Workspace(ctx context.Context) (*models.Workspace, error) {
	tc := tenant.MustGet(ctx)

	var ws models.Workspace
	err := r.TenantDB.QueryRow(ctx,
		`SELECT id, slug, name, status, ca_cert_pem, created_at, updated_at
		 FROM workspaces
		 WHERE id = $1`,
		tc.TenantID,
	).Scan(
		&ws.ID, &ws.Slug, &ws.Name,
		&ws.Status, &ws.CACertPEM,
		&ws.CreatedAt, &ws.UpdatedAt,
	)
	if err != nil {
		return nil, fmt.Errorf("workspace: %w", err)
	}

	return &ws, nil
}

// LookupWorkspace is the resolver for the lookupWorkspace field.
// Public query — no JWT required. Used by signup to check slug availability.
// Only exposes {id, name, slug} via WorkspacePublic.
func (r *queryResolver) LookupWorkspace(ctx context.Context, slug string) (*graph.WorkspaceLookupResult, error) {
	var ws graph.WorkspacePublic
	err := r.Pool.QueryRow(ctx,
		`SELECT id, name, slug FROM workspaces
		  WHERE slug = $1 AND status = 'active'`,
		slug,
	).Scan(&ws.ID, &ws.Name, &ws.Slug)
	if errors.Is(err, pgx.ErrNoRows) {
		return &graph.WorkspaceLookupResult{Found: false, Workspace: nil}, nil
	}
	if err != nil {
		return nil, fmt.Errorf("lookup workspace: %w", err)
	}
	return &graph.WorkspaceLookupResult{Found: true, Workspace: &ws}, nil
}

// LookupWorkspacesByEmail is the resolver for the lookupWorkspacesByEmail field.
// Public query — no JWT required. Lists active workspaces a given email belongs to.
// Used by the login page for returning users to pick a workspace.
func (r *queryResolver) LookupWorkspacesByEmail(ctx context.Context, email string) (*graph.WorkspaceListResult, error) {
	rows, err := r.Pool.Query(ctx,
		`SELECT DISTINCT w.id, w.name, w.slug
		   FROM workspaces w
		   JOIN users u ON u.tenant_id = w.id
		  WHERE u.email = $1
		    AND u.status = 'active'
		    AND w.status = 'active'
		  ORDER BY w.name`,
		email,
	)
	if err != nil {
		return nil, fmt.Errorf("lookup workspaces by email: %w", err)
	}
	defer rows.Close()

	result := &graph.WorkspaceListResult{Workspaces: []*graph.WorkspacePublic{}}
	for rows.Next() {
		var ws graph.WorkspacePublic
		if err := rows.Scan(&ws.ID, &ws.Name, &ws.Slug); err != nil {
			return nil, fmt.Errorf("scan workspace: %w", err)
		}
		result.Workspaces = append(result.Workspaces, &ws)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("iterate workspaces: %w", err)
	}
	return result, nil
}

// Role is the resolver for the role field.
func (r *userResolver) Role(ctx context.Context, obj *models.User) (graph.Role, error) {
	role := graph.Role(strings.ToUpper(obj.Role))
	if !role.IsValid() {
		return "", fmt.Errorf("invalid role: %q", obj.Role)
	}

	return role, nil
}

// CreatedAt is the resolver for the createdAt field.
func (r *userResolver) CreatedAt(ctx context.Context, obj *models.User) (string, error) {
	return obj.CreatedAt.Format("2006-01-02T15:04:05Z07:00"), nil
}

// Status is the resolver for the status field.
func (r *workspaceResolver) Status(ctx context.Context, obj *models.Workspace) (graph.WorkspaceStatus, error) {
	status := graph.WorkspaceStatus(strings.ToUpper(obj.Status))
	if !status.IsValid() {
		return "", fmt.Errorf("invalid workspace status: %q", obj.Status)
	}

	return status, nil
}

// CreatedAt is the resolver for the createdAt field.
func (r *workspaceResolver) CreatedAt(ctx context.Context, obj *models.Workspace) (string, error) {
	return obj.CreatedAt.Format("2006-01-02T15:04:05Z07:00"), nil
}

// Mutation returns graph.MutationResolver implementation.
func (r *Resolver) Mutation() graph.MutationResolver { return &mutationResolver{r} }

// Query returns graph.QueryResolver implementation.
func (r *Resolver) Query() graph.QueryResolver { return &queryResolver{r} }

// User returns graph.UserResolver implementation.
func (r *Resolver) User() graph.UserResolver { return &userResolver{r} }

// Workspace returns graph.WorkspaceResolver implementation.
func (r *Resolver) Workspace() graph.WorkspaceResolver { return &workspaceResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type userResolver struct{ *Resolver }
type workspaceResolver struct{ *Resolver }
