package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"fmt"

	"github.com/yourorg/ztna/controller/graph"
)

// GenerateShieldToken is the resolver for the generateShieldToken field.
func (r *mutationResolver) GenerateShieldToken(ctx context.Context, remoteNetworkID string, shieldName string) (*graph.ShieldToken, error) {
	panic(fmt.Errorf("not implemented: GenerateShieldToken - generateShieldToken"))
}

// RevokeShield is the resolver for the revokeShield field.
func (r *mutationResolver) RevokeShield(ctx context.Context, id string) (bool, error) {
	panic(fmt.Errorf("not implemented: RevokeShield - revokeShield"))
}

// DeleteShield is the resolver for the deleteShield field.
func (r *mutationResolver) DeleteShield(ctx context.Context, id string) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteShield - deleteShield"))
}

// Shields is the resolver for the shields field.
func (r *queryResolver) Shields(ctx context.Context, remoteNetworkID string) ([]*graph.Shield, error) {
	panic(fmt.Errorf("not implemented: Shields - shields"))
}

// Shield is the resolver for the shield field.
func (r *queryResolver) Shield(ctx context.Context, id string) (*graph.Shield, error) {
	panic(fmt.Errorf("not implemented: Shield - shield"))
}
