// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: proto/connector/connector.proto

package connector

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnrollRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EnrollmentToken string                 `protobuf:"bytes,1,opt,name=enrollment_token,json=enrollmentToken,proto3" json:"enrollment_token,omitempty"` // signed JWT — single-use enrollment token
	CsrDer          []byte                 `protobuf:"bytes,2,opt,name=csr_der,json=csrDer,proto3" json:"csr_der,omitempty"`                            // DER-encoded PKCS#10 CSR (EC P-384)
	Version         string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`                                        // CARGO_PKG_VERSION
	Hostname        string                 `protobuf:"bytes,4,opt,name=hostname,proto3" json:"hostname,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EnrollRequest) Reset() {
	*x = EnrollRequest{}
	mi := &file_proto_connector_connector_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollRequest) ProtoMessage() {}

func (x *EnrollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_connector_connector_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollRequest.ProtoReflect.Descriptor instead.
func (*EnrollRequest) Descriptor() ([]byte, []int) {
	return file_proto_connector_connector_proto_rawDescGZIP(), []int{0}
}

func (x *EnrollRequest) GetEnrollmentToken() string {
	if x != nil {
		return x.EnrollmentToken
	}
	return ""
}

func (x *EnrollRequest) GetCsrDer() []byte {
	if x != nil {
		return x.CsrDer
	}
	return nil
}

func (x *EnrollRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *EnrollRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

type EnrollResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	CertificatePem    []byte                 `protobuf:"bytes,1,opt,name=certificate_pem,json=certificatePem,proto3" json:"certificate_pem,omitempty"`            // signed leaf cert — 7-day validity, SPIFFE SAN
	WorkspaceCaPem    []byte                 `protobuf:"bytes,2,opt,name=workspace_ca_pem,json=workspaceCaPem,proto3" json:"workspace_ca_pem,omitempty"`          // WorkspaceCA cert (PEM)
	IntermediateCaPem []byte                 `protobuf:"bytes,3,opt,name=intermediate_ca_pem,json=intermediateCaPem,proto3" json:"intermediate_ca_pem,omitempty"` // Intermediate CA cert (PEM)
	ConnectorId       string                 `protobuf:"bytes,4,opt,name=connector_id,json=connectorId,proto3" json:"connector_id,omitempty"`                     // confirmed connector UUID
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *EnrollResponse) Reset() {
	*x = EnrollResponse{}
	mi := &file_proto_connector_connector_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollResponse) ProtoMessage() {}

func (x *EnrollResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_connector_connector_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollResponse.ProtoReflect.Descriptor instead.
func (*EnrollResponse) Descriptor() ([]byte, []int) {
	return file_proto_connector_connector_proto_rawDescGZIP(), []int{1}
}

func (x *EnrollResponse) GetCertificatePem() []byte {
	if x != nil {
		return x.CertificatePem
	}
	return nil
}

func (x *EnrollResponse) GetWorkspaceCaPem() []byte {
	if x != nil {
		return x.WorkspaceCaPem
	}
	return nil
}

func (x *EnrollResponse) GetIntermediateCaPem() []byte {
	if x != nil {
		return x.IntermediateCaPem
	}
	return nil
}

func (x *EnrollResponse) GetConnectorId() string {
	if x != nil {
		return x.ConnectorId
	}
	return ""
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConnectorId   string                 `protobuf:"bytes,1,opt,name=connector_id,json=connectorId,proto3" json:"connector_id,omitempty"` // for logging only — NOT authoritative identity
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`                            // CARGO_PKG_VERSION
	Hostname      string                 `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	PublicIp      string                 `protobuf:"bytes,4,opt,name=public_ip,json=publicIp,proto3" json:"public_ip,omitempty"` // optional
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_proto_connector_connector_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_connector_connector_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_proto_connector_connector_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatRequest) GetConnectorId() string {
	if x != nil {
		return x.ConnectorId
	}
	return ""
}

func (x *HeartbeatRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HeartbeatRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *HeartbeatRequest) GetPublicIp() string {
	if x != nil {
		return x.PublicIp
	}
	return ""
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	LatestVersion string                 `protobuf:"bytes,2,opt,name=latest_version,json=latestVersion,proto3" json:"latest_version,omitempty"` // controller informs connector of latest release
	ReEnroll      bool                   `protobuf:"varint,3,opt,name=re_enroll,json=reEnroll,proto3" json:"re_enroll,omitempty"`               // always false this sprint — field plumbed for next sprint
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_proto_connector_connector_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_connector_connector_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_proto_connector_connector_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *HeartbeatResponse) GetLatestVersion() string {
	if x != nil {
		return x.LatestVersion
	}
	return ""
}

func (x *HeartbeatResponse) GetReEnroll() bool {
	if x != nil {
		return x.ReEnroll
	}
	return false
}

var File_proto_connector_connector_proto protoreflect.FileDescriptor

const file_proto_connector_connector_proto_rawDesc = "" +
	"\n" +
	"\x1fproto/connector/connector.proto\x12\tconnector\"\x89\x01\n" +
	"\rEnrollRequest\x12)\n" +
	"\x10enrollment_token\x18\x01 \x01(\tR\x0fenrollmentToken\x12\x17\n" +
	"\acsr_der\x18\x02 \x01(\fR\x06csrDer\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x1a\n" +
	"\bhostname\x18\x04 \x01(\tR\bhostname\"\xb6\x01\n" +
	"\x0eEnrollResponse\x12'\n" +
	"\x0fcertificate_pem\x18\x01 \x01(\fR\x0ecertificatePem\x12(\n" +
	"\x10workspace_ca_pem\x18\x02 \x01(\fR\x0eworkspaceCaPem\x12.\n" +
	"\x13intermediate_ca_pem\x18\x03 \x01(\fR\x11intermediateCaPem\x12!\n" +
	"\fconnector_id\x18\x04 \x01(\tR\vconnectorId\"\x88\x01\n" +
	"\x10HeartbeatRequest\x12!\n" +
	"\fconnector_id\x18\x01 \x01(\tR\vconnectorId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\tR\bhostname\x12\x1b\n" +
	"\tpublic_ip\x18\x04 \x01(\tR\bpublicIp\"g\n" +
	"\x11HeartbeatResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12%\n" +
	"\x0elatest_version\x18\x02 \x01(\tR\rlatestVersion\x12\x1b\n" +
	"\tre_enroll\x18\x03 \x01(\bR\breEnroll2\x99\x01\n" +
	"\x10ConnectorService\x12=\n" +
	"\x06Enroll\x12\x18.connector.EnrollRequest\x1a\x19.connector.EnrollResponse\x12F\n" +
	"\tHeartbeat\x12\x1b.connector.HeartbeatRequest\x1a\x1c.connector.HeartbeatResponseB4Z2github.com/yourorg/ztna/controller/proto/connectorb\x06proto3"

var (
	file_proto_connector_connector_proto_rawDescOnce sync.Once
	file_proto_connector_connector_proto_rawDescData []byte
)

func file_proto_connector_connector_proto_rawDescGZIP() []byte {
	file_proto_connector_connector_proto_rawDescOnce.Do(func() {
		file_proto_connector_connector_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_connector_connector_proto_rawDesc), len(file_proto_connector_connector_proto_rawDesc)))
	})
	return file_proto_connector_connector_proto_rawDescData
}

var file_proto_connector_connector_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_connector_connector_proto_goTypes = []any{
	(*EnrollRequest)(nil),     // 0: connector.EnrollRequest
	(*EnrollResponse)(nil),    // 1: connector.EnrollResponse
	(*HeartbeatRequest)(nil),  // 2: connector.HeartbeatRequest
	(*HeartbeatResponse)(nil), // 3: connector.HeartbeatResponse
}
var file_proto_connector_connector_proto_depIdxs = []int32{
	0, // 0: connector.ConnectorService.Enroll:input_type -> connector.EnrollRequest
	2, // 1: connector.ConnectorService.Heartbeat:input_type -> connector.HeartbeatRequest
	1, // 2: connector.ConnectorService.Enroll:output_type -> connector.EnrollResponse
	3, // 3: connector.ConnectorService.Heartbeat:output_type -> connector.HeartbeatResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_connector_connector_proto_init() }
func file_proto_connector_connector_proto_init() {
	if File_proto_connector_connector_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_connector_connector_proto_rawDesc), len(file_proto_connector_connector_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_connector_connector_proto_goTypes,
		DependencyIndexes: file_proto_connector_connector_proto_depIdxs,
		MessageInfos:      file_proto_connector_connector_proto_msgTypes,
	}.Build()
	File_proto_connector_connector_proto = out.File
	file_proto_connector_connector_proto_goTypes = nil
	file_proto_connector_connector_proto_depIdxs = nil
}
