// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type Connector struct {
	ID              string          `json:"id"`
	Name            string          `json:"name"`
	Status          ConnectorStatus `json:"status"`
	RemoteNetworkID string          `json:"remoteNetworkId"`
	LastSeenAt      *string         `json:"lastSeenAt,omitempty"`
	Version         *string         `json:"version,omitempty"`
	Hostname        *string         `json:"hostname,omitempty"`
	PublicIP        *string         `json:"publicIp,omitempty"`
	LanAddr         *string         `json:"lanAddr,omitempty"`
	CertNotAfter    *string         `json:"certNotAfter,omitempty"`
	CreatedAt       string          `json:"createdAt"`
}

type ConnectorToken struct {
	ConnectorID    string `json:"connectorId"`
	InstallCommand string `json:"installCommand"`
}

type CreateResourceInput struct {
	RemoteNetworkID string  `json:"remoteNetworkId"`
	Name            string  `json:"name"`
	Description     *string `json:"description,omitempty"`
	Host            string  `json:"host"`
	Protocol        string  `json:"protocol"`
	PortFrom        int     `json:"portFrom"`
	PortTo          int     `json:"portTo"`
}

type Mutation struct {
}

type Query struct {
}

type RemoteNetwork struct {
	ID            string              `json:"id"`
	Name          string              `json:"name"`
	Location      NetworkLocation     `json:"location"`
	Status        RemoteNetworkStatus `json:"status"`
	Connectors    []*Connector        `json:"connectors"`
	NetworkHealth NetworkHealth       `json:"networkHealth"`
	Shields       []*Shield           `json:"shields"`
	CreatedAt     string              `json:"createdAt"`
}

type Resource struct {
	ID             string         `json:"id"`
	Name           string         `json:"name"`
	Description    *string        `json:"description,omitempty"`
	Host           string         `json:"host"`
	Protocol       string         `json:"protocol"`
	PortFrom       int            `json:"portFrom"`
	PortTo         int            `json:"portTo"`
	Status         string         `json:"status"`
	ErrorMessage   *string        `json:"errorMessage,omitempty"`
	AppliedAt      *string        `json:"appliedAt,omitempty"`
	LastVerifiedAt *string        `json:"lastVerifiedAt,omitempty"`
	CreatedAt      string         `json:"createdAt"`
	Shield         *Shield        `json:"shield,omitempty"`
	RemoteNetwork  *RemoteNetwork `json:"remoteNetwork"`
}

type Shield struct {
	ID              string       `json:"id"`
	Name            string       `json:"name"`
	Status          ShieldStatus `json:"status"`
	RemoteNetworkID string       `json:"remoteNetworkId"`
	ConnectorID     string       `json:"connectorId"`
	LastSeenAt      *string      `json:"lastSeenAt,omitempty"`
	Version         *string      `json:"version,omitempty"`
	Hostname        *string      `json:"hostname,omitempty"`
	LanIP           *string      `json:"lanIp,omitempty"`
	InterfaceAddr   *string      `json:"interfaceAddr,omitempty"`
	CertNotAfter    *string      `json:"certNotAfter,omitempty"`
	CreatedAt       string       `json:"createdAt"`
}

type ShieldToken struct {
	ShieldID       string `json:"shieldId"`
	InstallCommand string `json:"installCommand"`
}

type WorkspaceListResult struct {
	Workspaces []*WorkspacePublic `json:"workspaces"`
}

type WorkspaceLookupResult struct {
	Found     bool             `json:"found"`
	Workspace *WorkspacePublic `json:"workspace,omitempty"`
}

type WorkspacePublic struct {
	ID   string `json:"id"`
	Name string `json:"name"`
	Slug string `json:"slug"`
}

type ConnectorStatus string

const (
	ConnectorStatusPending      ConnectorStatus = "PENDING"
	ConnectorStatusActive       ConnectorStatus = "ACTIVE"
	ConnectorStatusDisconnected ConnectorStatus = "DISCONNECTED"
	ConnectorStatusRevoked      ConnectorStatus = "REVOKED"
)

var AllConnectorStatus = []ConnectorStatus{
	ConnectorStatusPending,
	ConnectorStatusActive,
	ConnectorStatusDisconnected,
	ConnectorStatusRevoked,
}

func (e ConnectorStatus) IsValid() bool {
	switch e {
	case ConnectorStatusPending, ConnectorStatusActive, ConnectorStatusDisconnected, ConnectorStatusRevoked:
		return true
	}
	return false
}

func (e ConnectorStatus) String() string {
	return string(e)
}

func (e *ConnectorStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ConnectorStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ConnectorStatus", str)
	}
	return nil
}

func (e ConnectorStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ConnectorStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ConnectorStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type NetworkHealth string

const (
	NetworkHealthOnline   NetworkHealth = "ONLINE"
	NetworkHealthDegraded NetworkHealth = "DEGRADED"
	NetworkHealthOffline  NetworkHealth = "OFFLINE"
)

var AllNetworkHealth = []NetworkHealth{
	NetworkHealthOnline,
	NetworkHealthDegraded,
	NetworkHealthOffline,
}

func (e NetworkHealth) IsValid() bool {
	switch e {
	case NetworkHealthOnline, NetworkHealthDegraded, NetworkHealthOffline:
		return true
	}
	return false
}

func (e NetworkHealth) String() string {
	return string(e)
}

func (e *NetworkHealth) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = NetworkHealth(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid NetworkHealth", str)
	}
	return nil
}

func (e NetworkHealth) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *NetworkHealth) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e NetworkHealth) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type NetworkLocation string

const (
	NetworkLocationHome   NetworkLocation = "HOME"
	NetworkLocationOffice NetworkLocation = "OFFICE"
	NetworkLocationAWS    NetworkLocation = "AWS"
	NetworkLocationGCP    NetworkLocation = "GCP"
	NetworkLocationAzure  NetworkLocation = "AZURE"
	NetworkLocationOther  NetworkLocation = "OTHER"
)

var AllNetworkLocation = []NetworkLocation{
	NetworkLocationHome,
	NetworkLocationOffice,
	NetworkLocationAWS,
	NetworkLocationGCP,
	NetworkLocationAzure,
	NetworkLocationOther,
}

func (e NetworkLocation) IsValid() bool {
	switch e {
	case NetworkLocationHome, NetworkLocationOffice, NetworkLocationAWS, NetworkLocationGCP, NetworkLocationAzure, NetworkLocationOther:
		return true
	}
	return false
}

func (e NetworkLocation) String() string {
	return string(e)
}

func (e *NetworkLocation) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = NetworkLocation(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid NetworkLocation", str)
	}
	return nil
}

func (e NetworkLocation) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *NetworkLocation) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e NetworkLocation) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type RemoteNetworkStatus string

const (
	RemoteNetworkStatusActive  RemoteNetworkStatus = "ACTIVE"
	RemoteNetworkStatusDeleted RemoteNetworkStatus = "DELETED"
)

var AllRemoteNetworkStatus = []RemoteNetworkStatus{
	RemoteNetworkStatusActive,
	RemoteNetworkStatusDeleted,
}

func (e RemoteNetworkStatus) IsValid() bool {
	switch e {
	case RemoteNetworkStatusActive, RemoteNetworkStatusDeleted:
		return true
	}
	return false
}

func (e RemoteNetworkStatus) String() string {
	return string(e)
}

func (e *RemoteNetworkStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = RemoteNetworkStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid RemoteNetworkStatus", str)
	}
	return nil
}

func (e RemoteNetworkStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *RemoteNetworkStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e RemoteNetworkStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type Role string

const (
	RoleAdmin  Role = "ADMIN"
	RoleMember Role = "MEMBER"
	RoleViewer Role = "VIEWER"
)

var AllRole = []Role{
	RoleAdmin,
	RoleMember,
	RoleViewer,
}

func (e Role) IsValid() bool {
	switch e {
	case RoleAdmin, RoleMember, RoleViewer:
		return true
	}
	return false
}

func (e Role) String() string {
	return string(e)
}

func (e *Role) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Role(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Role", str)
	}
	return nil
}

func (e Role) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Role) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Role) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ShieldStatus string

const (
	ShieldStatusPending      ShieldStatus = "PENDING"
	ShieldStatusActive       ShieldStatus = "ACTIVE"
	ShieldStatusDisconnected ShieldStatus = "DISCONNECTED"
	ShieldStatusRevoked      ShieldStatus = "REVOKED"
)

var AllShieldStatus = []ShieldStatus{
	ShieldStatusPending,
	ShieldStatusActive,
	ShieldStatusDisconnected,
	ShieldStatusRevoked,
}

func (e ShieldStatus) IsValid() bool {
	switch e {
	case ShieldStatusPending, ShieldStatusActive, ShieldStatusDisconnected, ShieldStatusRevoked:
		return true
	}
	return false
}

func (e ShieldStatus) String() string {
	return string(e)
}

func (e *ShieldStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ShieldStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ShieldStatus", str)
	}
	return nil
}

func (e ShieldStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ShieldStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ShieldStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type WorkspaceStatus string

const (
	WorkspaceStatusProvisioning WorkspaceStatus = "PROVISIONING"
	WorkspaceStatusActive       WorkspaceStatus = "ACTIVE"
	WorkspaceStatusSuspended    WorkspaceStatus = "SUSPENDED"
	WorkspaceStatusDeleted      WorkspaceStatus = "DELETED"
)

var AllWorkspaceStatus = []WorkspaceStatus{
	WorkspaceStatusProvisioning,
	WorkspaceStatusActive,
	WorkspaceStatusSuspended,
	WorkspaceStatusDeleted,
}

func (e WorkspaceStatus) IsValid() bool {
	switch e {
	case WorkspaceStatusProvisioning, WorkspaceStatusActive, WorkspaceStatusSuspended, WorkspaceStatusDeleted:
		return true
	}
	return false
}

func (e WorkspaceStatus) String() string {
	return string(e)
}

func (e *WorkspaceStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = WorkspaceStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid WorkspaceStatus", str)
	}
	return nil
}

func (e WorkspaceStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *WorkspaceStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e WorkspaceStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
