// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type AuthInitPayload struct {
	RedirectURL string `json:"redirectUrl"`
	State       string `json:"state"`
}

type Mutation struct {
}

type Query struct {
}

type Role string

const (
	RoleAdmin  Role = "ADMIN"
	RoleMember Role = "MEMBER"
	RoleViewer Role = "VIEWER"
)

var AllRole = []Role{
	RoleAdmin,
	RoleMember,
	RoleViewer,
}

func (e Role) IsValid() bool {
	switch e {
	case RoleAdmin, RoleMember, RoleViewer:
		return true
	}
	return false
}

func (e Role) String() string {
	return string(e)
}

func (e *Role) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Role(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Role", str)
	}
	return nil
}

func (e Role) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Role) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Role) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type WorkspaceStatus string

const (
	WorkspaceStatusProvisioning WorkspaceStatus = "PROVISIONING"
	WorkspaceStatusActive       WorkspaceStatus = "ACTIVE"
	WorkspaceStatusSuspended    WorkspaceStatus = "SUSPENDED"
	WorkspaceStatusDeleted      WorkspaceStatus = "DELETED"
)

var AllWorkspaceStatus = []WorkspaceStatus{
	WorkspaceStatusProvisioning,
	WorkspaceStatusActive,
	WorkspaceStatusSuspended,
	WorkspaceStatusDeleted,
}

func (e WorkspaceStatus) IsValid() bool {
	switch e {
	case WorkspaceStatusProvisioning, WorkspaceStatusActive, WorkspaceStatusSuspended, WorkspaceStatusDeleted:
		return true
	}
	return false
}

func (e WorkspaceStatus) String() string {
	return string(e)
}

func (e *WorkspaceStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = WorkspaceStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid WorkspaceStatus", str)
	}
	return nil
}

func (e WorkspaceStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *WorkspaceStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e WorkspaceStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
